webiny/webiny-js

packages/webiny-ui/src/List/DataList/DataList.js
A "0" would be outputted in the pagination section if there were no records to show.
=> fix: 🐛  Fix incorrect pagination info in DataList component.

packages/webiny-entity/__tests__/events.test.js, packages/webiny-entity/src/entity.js, packages/webiny-entity/src/entityAttributes/entitiesAttribute.js, packages/webiny-entity/src/entityAttributes/entitiesAttributeValue.js, packages/webiny-entity/src/entityAttributes/entityAttribute.js
These events must be executed outside save process. 
This means that once the save starts, immediately execute `beforeSave`, `beforeUpdate`, `beforeCreate` events, and only then start the actual processing of entity. The same goes for "after" events, execute them once processing has been completely done.
This was done simply by renaming current `before` and `after` events to `__before` and `__after`, making them internal events, and inserting new ones that follow the explained behavior.
Motivation:
Eg. `onAfterCreate` developer again calls `this.save()`, this save call would not work. Entity was still in "processing" state, and method would immediately return.
=> Ensure before / after events are executed independently

packages/webiny-entity-mysql/__tests__/count.test.js, packages/webiny-entity-mysql/__tests__/find.test.js, packages/webiny-entity-mysql/__tests__/findOne.test.js, packages/webiny-entity-mysql/__tests__/statements/select.test.js, packages/webiny-entity-mysql/src/mysqlDriver.js, packages/webiny-entity-mysql/src/statements/select.js, packages/webiny-entity-mysql/src/statements/statement.js
Now you can use `groupBy` parameter, in order to group queried data. Eg. 
```
await SimpleEntity.findOne({ groupBy: ["something"] });
```
You can use this in `find`, `findOne` and `count` methods.
=> Implemented "groupBy" option

packages/webiny-entity-mysql/__tests__/count.test.js, packages/webiny-entity-mysql/__tests__/find.test.js, packages/webiny-entity-mysql/__tests__/findOne.test.js, packages/webiny-entity-mysql/src/mysqlDriver.js, packages/webiny-entity-mysql/src/statements/select.js, packages/webiny-entity-mysql/src/statements/statement.js
Example:
```
await SimpleEntity.count({
sql: {
query: "SELECT COUNT(*) FROM `SimpleEntity` WHERE age > ? OR type = ?",
values: [20, "developer"]
},
groupBy: ["something"]
});
```
Note that in this example `groupBy` will totally be ignored, because the custom `sql` was passed.
This behavior is supported by `find`, `findOne` and `count` methods.
=> Added ability to pass custom SQL queries into find methods.

packages/webiny-entity/__tests__/attributes/entitiesAttributes/withoutStorage/using/autoDeleteSave.test.js, packages/webiny-entity/__tests__/attributes/entityAttribute/delete.test.js, packages/webiny-entity/__tests__/entities/abcDynamicAttribute.js, packages/webiny-entity/__tests__/entities/entitiesUsingDynamic.js, packages/webiny-entity/src/entityAttributes/entitiesAttribute.js, packages/webiny-entity/src/entityAttributes/entityAttribute.js
Normally in entity / entities attributes, certain save / delete processes must occur once the main entity is being saved / deleted. This is because links need to be validated and properly managed.
But, if entity / entities attributes are marked as dynamic, value is always returned by provided callback, eg.:
```
this.attr("revisions")
.entities(Page)
.setDynamic(() => {
return Page.find({ query: { parent: this.parent }, sort: { version: -1 } });
});
```
Also, these cannot have value assigned.
So in these cases, when entity / entities attributes are dynamic, mentioned save / deleted processes must not occur at all.
=> Entity / entities attributes - fixed save / delete behavior when set as dynamic

packages/webiny-entity-mysql/__tests__/save.test.js, packages/webiny-entity-mysql/src/mysqlDriver.js
If for some reason you would like to manually assign an ID (instead of receiving an automatic and randomly generated one), you can now assign it by yourself, before you call `save` and it will be used.
Just make sure it's a valid ID (MongoDB format) - `^[0-9a-fA-F]{24}$`. Otherwise an error will be thrown.
=> Added ability to manually assign an ID before saving a new entity

packages/webiny-api-cms/src/dataSource/schemas/pageResolvers/listPages.js, packages/webiny-api/src/graphql/crudResolvers.js, packages/webiny-api/src/graphql/schema/genericTypes.js, packages/webiny-app-admin/src/views/ApiTokens/graphql.js, packages/webiny-app-admin/src/views/Groups/graphql.js, packages/webiny-app-admin/src/views/Roles/graphql.js, packages/webiny-app-admin/src/views/Users/graphql.js, packages/webiny-app-cms/src/admin/graphql/pages.js, packages/webiny-app-cms/src/admin/views/Categories/graphql.js, packages/webiny-entity-mysql/src/mysqlDriver.js, packages/webiny-entity/__tests__/createPaginationMeta.test.js, packages/webiny-entity/__tests__/entityCollection.test.js, packages/webiny-entity/index.js, packages/webiny-entity/src/createPaginationMeta.js, packages/webiny-entity/src/entity.js, packages/webiny-entity/src/index.js
This can be used to manually create pagination meta.
Example:
```
import { createPaginationMeta } from "webiny-entity";
let meta = createPaginationMeta({
page: 1,
perPage: 10,
totalCount: 100
});
```
=> Added "createPaginationMeta" helper function for manual creation of pagination meta

packages/webiny-install/README.md, packages/webiny-load-assets/.babelrc, packages/webiny-load-assets/README.md, packages/webiny-load-assets/index.js, packages/webiny-load-assets/package.json, packages/webiny-load-assets/src/argumentProcessors/index.js, packages/webiny-load-assets/src/argumentProcessors/stringArgumentProcessor.js, packages/webiny-load-assets/src/assetLoaders/index.js, packages/webiny-load-assets/src/assetLoaders/linkLoader.js, packages/webiny-load-assets/src/assetLoaders/scriptLoader.js, packages/webiny-load-assets/src/index.js, packages/webiny-load-assets/types.js
A small library for easy loading additional scripts and links (eg. stylesheets).
Example:
```javascript
load(
"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css",
"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"
).then(() => {
window.cookieconsent.initialise({
palette: {
popup: {
background: "#000"
},
button: {
background: "#f1d600"
}
}
});
});
```
=> Created "webiny-load-assets" package for easier inclusion of additional scripts and links (eg. stylesheets)

idea.js, packages/demo-admin/src/config/development.js, packages/demo-admin/src/config/production.js, packages/webiny-react-router/package.json, packages/webiny-react-router/src/Router.cmp.js, packages/webiny-react-router/src/Router.js, yarn.lock
This PR fixes rendering of default route and also closes #326 and closes #266.
404 route is not necessary as a config parameter, as `defaultRoute` is the route that will be rendered if no other route matches the request. Technically it is the same thing as 404.
=> Handle default route rendering and remove dependency on jQuery

packages/demo-theme/src/layouts/static.js, packages/webiny-app/src/components/Addons.js, packages/webiny-app/src/components/index.js
Integrations and apps are types of "addons". That's why this component was renamed.
=> Renamed "Modules" component to "Addons"

packages/webiny-api-cms/src/entities/Page.entity.js, packages/webiny-app-cms/src/admin/plugins/pageDetails/header/editRevision/EditRevision.js, packages/webiny-app-cms/src/admin/plugins/pageDetails/pageRevisions/Revision.js
Before this fix, each revision would get a new URL, eg: `/untitled-5c20ef0946e6daf6d952c53c`, which is not what we want.
Fixes #338.
=> When creating a new revision, page URL will be preserved.

packages/webiny-ui/src/Grid/Grid.js
This is necessary as @rmwc/grid uses that property to determine whether GridInner needs to be added or not.
=> Add displayName to GridInner component.

packages/webiny-api/src/lambda/lambda.js, packages/webiny-entity/__tests__/attributes/entityAttribute/general.test.js, packages/webiny-entity/src/entity.js, packages/webiny-entity/src/entityAttributes/entitiesAttribute.js, packages/webiny-entity/src/entityAttributes/entitiesAttributeValue.js, packages/webiny-entity/src/entityAttributes/entityAttribute.js, packages/webiny-entity/src/entityAttributes/entityAttributeValue.js, packages/webiny-entity/src/entityCollection.js, packages/webiny-entity/src/entityPool.js
Problems occurred after the code was built. This was the safer approach since strings are not touched in the process.
=> Instead of checking instance types via `instanceof`, `classId` is now used (more reliable)

addons/webiny-integration-cookie-policy/package.json
A production dependency was listed in `devDependencies` thus breaking the npm package on release.
=> Move production dependency to "dependencies".

packages/webiny-api-cms/.babelrc, packages/webiny-api-cms/package.json, packages/webiny-api-cms/src/install/plugins/importData/createDefaultBlocks.js, packages/webiny-api-cms/src/install/plugins/setupEntities.js, packages/webiny-api-cms/src/plugins/graphql/menuResolvers/prepareMenuItems.js, packages/webiny-api-cms/src/plugins/graphql/pageResolvers/listPublishedPages.js, packages/webiny-api-security/src/entities/User.entity.js, packages/webiny-api-security/src/install/plugins/importData.js, packages/webiny-api-security/src/install/plugins/setupEntities.js, packages/webiny-api-security/src/plugins/graphql/userResolvers/loginUser.js, packages/webiny-api-security/src/plugins/security.js, packages/webiny-api/package.json, packages/webiny-api/src/graphql/InvalidAttributesError.js, packages/webiny-api/src/graphql/parseBoolean.js
It is now possible to pass `security.admin` object through the installation context to create a root user with specified email and password. Also, we can now turn off file copying of CMS, via `cms.copyFiles` context key.
=> Add control flags to installation process of Security and CMS.

packages/webiny-api/src/lambda/lambda.js
This is a problem inherited from `graphql-tools` when using `addSchemaLevelResolveFunction`. `__runAtMostOnce` flag blocks root schema resolver to execute on subsequent requests, which in case of Lambda is fatal. So we unset the flag to allow subsequent requests to be processed with the root resolver.
=> Unset __runAtMostOnce flag in root schema resolver.

packages/webiny-api-cms/src/entities/Page.entity.js, packages/webiny-app-cms/src/editor/plugins/pageSettings/components/GeneralSettings.js, packages/webiny-model/__tests__/attributes/model.test.js, packages/webiny-model/src/attributes/modelAttribute.js, packages/webiny-model/src/attributes/modelsAttribute.js, packages/webiny-model/src/model.js
Upon creating a new page revision, data in both `snippet` and `settings` attributes in source page would not be copied to the new revision. This PR fixes this.
=> When creating a new revision, all data is now copied correctly.

independent/webiny-integration-google-tag-manager/src/plugins/api/index.js, independent/webiny-integration-mailchimp/src/plugins/api/index.js, packages/demo-api/src/configs/development.js, packages/demo-api/src/configs/production.js, packages/webiny-api-cms/src/plugins/graphql.js
"scope" restrictions were applied to the whole settings, which means non-logged-in users wouldn't be able to load data like site name, social settings etc., even on the public site.
In the future, if there's a field that must not be exposed publicly, put a shield rule only for that specific field.
=> Site settings can now be queried by non-logged-in users too (for site)

packages/webiny-app-cms/src/admin/plugins/pageDetails/header/editRevision/EditRevision.js
We would switch between "pen" and "plus" icon, depending if the page is draft or not. By always showing the pen icon, we make it less confusing for the user. Pen icon is also more intuitive.
=> In page preview section (list of pages view), pen icon is always shown for editing (better UX)

packages/webiny-api-cms/src/plugins/graphql/menuResolvers/getMenuBySlug.js, packages/webiny-api-cms/src/plugins/graphql/pageResolvers/createRevisionFrom.js, packages/webiny-api-cms/src/plugins/graphql/pageResolvers/getPublishedPage.js, packages/webiny-api-security/src/plugins/graphql/userResolvers/getCurrentUser.js, packages/webiny-api-security/src/plugins/graphql/userResolvers/updateCurrentUser.js, packages/webiny-api/src/graphql/crudResolvers.js, packages/webiny-api/src/graphql/index.js, packages/webiny-api/src/graphql/responses.js
When creating custom GraphQL field resolvers, often times developers need to return a simple "record not found" error. To avoid manually creating the same error every time, a `NotFoundResponse` class was introduced. Consider the following example:
```javascript
import { Response, NotFoundResponse } from "webiny-api/graphql/responses";
(...)
const entity = await entityClass.findOne({ query: { slug } });
if (!entity) {
return new NotFoundResponse("Menu not found.");
}
```
Current `ErrorResponse` is still available.
=> Added "NotFoundResponse" class

packages/webiny-api/src/lambda/lambda.js
Fixes #490.
Sending a `GET` request to `/function/api` will open GraphQL Playground as expected. This is a built-in feature of Apollo so there is no reason to not support it.
Additionally, for some developers, this might also be the preferred way to inspect the GraphQL schema.
=> GraphQL Playground now works in development as expected

packages/webiny-app-cms/src/editor/plugins/slate/index.js, packages/webiny-app-cms/src/editor/plugins/slate/scroll/index.js
This PR fixes a problem with Slate editor regarding cursor position and autoscroll.
Slate does have the auto-scroll feature but our editor UI is slightly different and requires custom handling so a new `scroll` plugin is introduced to handle keystrokes and calculate position of the cursor and scroll the document if necessary.
=> Auto-scroll document when Slate cursor is outside the viewport.

packages/webiny-app-cms/src/editor/plugins/pageSettings/components/GeneralSettings.js, packages/webiny-app-cms/src/editor/plugins/pageSettings/components/SocialSettings.js, packages/webiny-app-cms/src/editor/plugins/pageSettings/components/appendOgImageDimensions.js
Since Facebook debugger shows warnings if `og:image:width` and `og:image:height` meta tags are not set, we decided to set them automatically, once an image was selected.
=> In Social Media page settings, once an image is selected, og:image:width and og:image:height meta tags will automatically be set 

packages/webiny-app/src/components/withFileUpload.js, packages/webiny-app/src/components/withImageUpload.js, packages/webiny-ui/src/ImageUpload/Image.js, yarn.lock
Previously, both `SingleImageUpload` and `MultiImageUpload` would just get disabled (transparent, no pointer events). Circular spinner looks better and it's easier to notice.
A snackbar message was also added.
=> Image components will show "Uploading..." snackbar and show circular spinner once the upload has started

packages/webiny-form/src/Form.js
Upon form submission, if a value of a form field was falsy, it would get changed to its default value, which in most cases is just `undefined` (no default value set). 
This has been fixed.
=> Form component - passed "onSubmit" data is now properly populated with default values

independent/webiny-integration-cookie-policy/src/plugins/render/index.js, independent/webiny-integration-cookie-policy/src/plugins/utils/showCookiePolicy.js
Even if you would disable the cookie policy banner, it would still get shown on the actual site.
Fixed the `if` statement that determines whether the banner should be shown or not.
=> Site will only show cookie policy banner if enabled via admin settings

independent/webiny-integration-cookie-policy/src/plugins/admin/components/CookiePolicySettings.js, independent/webiny-integration-cookie-policy/src/plugins/admin/components/getDefaultCookiePolicySettings.js
When enabling cookie policy integration, hitting preview without any initial values would show a transparent banner, which might confuse users.
We prepended default theme, from which users can do further alterations.
Following screenshot shows initial state of cookie policy settings, and previewed banner on bottom.
=> Added default theme for cookie-policy-integration.

packages/webiny-api-cms/src/plugins/graphql/menuResolvers/prepareMenuItems.js
When creating menus, if you were to select the "Page list" menu item type and then open the site, it would crash because of an API error (related to sorting of pages).
The issue was related to sorting, and it is now fixed.
=> "Page list" menu item type now works correctly on site

packages/demo-theme/src/style/elements/header-nav.scss, packages/demo-theme/src/style/elements/typography.scss
Closes #505 
Adjusted the default theme in a way that the body takes the definition of the base font-face, which then corrects the header font.
Browser, manual visual testing.
=> Fixed page title font style

packages/webiny-validation/__tests__/create.test.js, packages/webiny-validation/src/validation.js
Implemented `create` and `createSync` methods for creating reusable validator functions.
```
import { validation } from "webiny-validation";
const validate = validation.createSync("email");
try {
validate("test@webiny");
} catch (e) {
expect(e.message).toBe("Value must be a valid e-mail address.");
}
```
=> Added "create" and "createSync" methods

packages/webiny-app-cookie-policy/src/admin/components/CookiePolicySettings.js, packages/webiny-app-cookie-policy/src/utils/showCookiePolicy.js
While navigating on the site, cookie policy would reinitialize itself, rendering multiple banners.
Only initialize if not already initialized before.
N/A
=> Cookie policy banner doesn't reinitialize itself on every URL change

packages/webiny-api-cms/src/plugins/graphql/pageResolvers/listPages.js
Sorting pages doesn't work.
Fixed the MongoDB aggregation pipeline construction logic.
=> Fixed sorting of pages in CMS / List of pages

packages/webiny-app-typeform/src/admin/index.js
Typeform links not working.
There was an issue with saving the link in the element (incorrect path), which is now resolved.
Manual.
=> Fixed TypeForm CMS element

packages/webiny-app-cms/src/admin/plugins/pageDetails/pageRevisions/RevisionsList.js, packages/webiny-ui/src/Tabs/Tabs.js
Inactive tabs would unmount, which can cause issues. For example, when validating forms, we want to validate elements on all tabs, not just on the current one.
Instead of unmounting inactive tabs, we hide them with `display: none`. Please check the screenshot for the new functionality.
=> Tabs component - inactive tabs are now hidden instead of completely unmounted

packages/webiny-api-security/src/plugins/security.js
CMS schema supports addition of `typeDefs` and `resolvers` via plugins. However, we must also be able to add security rules via plugins. At this point `security` only supported an `object` as its value, and as such it was interpreted too early for other plugins to be registered.
This PR adds the ability to assign a function to schema plugin `security` key, and it will be executed at runtime, when all plugins have already been registered, and so we'll be able to use our plugin system to add `graphql-shield` rules.
```js
{
// ... other schema keys
security: () =>
merge(
{
shield: {
CmsQuery: {
getMenu: hasScope("cms:menu:crud")
},
CmsMutation: {
createMenu: hasScope("cms:menu:crud")
}
}
},
// Fetch plugins and merge with current security value
...getPlugins("cms-schema").map(pl => …
```
=> Support functions in schema security key.

packages/webiny-api-cms/src/plugins/graphql.js, packages/webiny-api-cookie-policy/src/index.js, packages/webiny-api-files/src/plugins/graphql.js, packages/webiny-api-google-tag-manager/src/index.js, packages/webiny-api-mailchimp/src/index.js, packages/webiny-api-security/src/plugins/graphql.js, packages/webiny-api-security/src/plugins/security.js, packages/webiny-api/src/graphql/schema/index.js, packages/webiny-api/src/lambda/lambda.js, packages/webiny-api/src/plugins/graphql.js, packages/webiny-api/src/types.js
Currently, schema plugins only support static definitions of schemas. There is a need for dynamic schema creation, so we can dynamically build schemas (typeDefs and resolvers).
`graphql-schema` plugin now supports `schema` value as plain object but also as an async function which must return the schema definition.
=> Add support for schema factory

.eslintrc.js, package.json, packages/api-files/src/plugins/resolvers/uploadFiles.js, yarn.lock
Fixes #579.
In `packages/api-files/src/plugins/resolvers/uploadFiles.js`, we had the following import:
`import getPreSignedPostPayload from "./utils/getPresignedPostPayload";`
The actual file is not `getPresignedPostPayload`, but `getPreSignedPostPayload`.
I fixed the import and additionally added the [eslint-plugin-import](https://www.npmjs.com/package/eslint-plugin-import), to prevent these kind of errors in the future.
N/A
=> Fixed incorrect import and added eslint rule to prevent future errors

packages/cli/create/template/package.json
Since we do not use `serverless` CLI directly, we don't need it as a dependency for the new project.
=> fix: remove "serverless" dependency from new project template.

packages/app-page-builder/src/admin/plugins/pageDetails/previewContent/PagePreview.js, packages/app-page-builder/src/editor/plugins/defaultBar/components/PublishPageButton/graphql.js
This PR fixes issues with updating the revisions list and revision content when selecting different revisions from the dropdown menu (see screenshot).
When doing a `publishRevision` mutation, we must require `id` and `published` in the response `data` fields so Apollo client can update its cache. That's, in general, a needed practice, we should avoid not-listing any `data` fields when doing updates (unless there is a good reason not to list any of course).
Added `id` and `published` fields in response data, so Apollo can update its cache. I also added the `key` prop to the `RenderElement` component, with the value of currently selected revision `id`, so the revision content gets re-rendered when selecting different revisions (`packages/app-page-builder/src/admin/plugins/pageDetails/preview …
=> Page Builder - fixes UI bugs in revisions list

packages/api-page-builder/src/plugins/models/pbPage.model.js
The publishing of pages did not work. This is because the `published` field in the `PbPage` model had `skipOnPopulate`, and `publishRevision` GQL field resolver just populates the page instance with `{ published: true}`. I checked the old `Page` entity, and the attribute did not have `skipOnPopulate` set, so this was a mistake in the refactoring process.
Removed the `skipOnPopulate` on the `published` field. Additionally, I removed 'published' key in the pages data in the PB installation ZIP file, since it's manually set after initial save (`packages/api-page-builder/src/plugins/graphql/installResolver/utils/savePages.js:47`).
N/A
=> Page Builder - Fix page publishing

packages/api-files/src/plugins/resolvers/uploadFile.js
The import is incorrect - it must be `getPresignedPostPayload`, instead of `getPreSignedPostPayload`.
Updated the import path.
N/A
=> Fixed another incorrect import of `getPresignedPostPayload` file

components/serverless-files/serverless.js, examples/api/serverless.yml, packages/api-files/src/plugins/resolvers/utils/getPresignedPostPayload.js, packages/cli/create/template/api/serverless.yml
Developers currently cannot adjust the minimum or maximum size of the uploaded file, it was hardcoded to 100B / 25MB
Developers can adjust this in the `serverless-files` component's `inputs` section, by providing `uploadMinFileSize` and `uploadMaxFileSize` values.
N/A
=> Enable configuring min / max size for file uploads

packages/app-admin/src/components/FileManager/FileDetails.js, packages/app-admin/src/components/FileManager/FileManagerView.js, packages/app-admin/src/components/FileManager/graphql.js
There were a few places in the File Manager UI that could use some improvements:
1. disable top right UPLOAD button while there is an active upload (screenshot below)
2. show file upload related error messages in snackbars (screenshot below)
3. refresh list of files after a file was deleted
All of the listed improvements are resolved.
1. disable top right UPLOAD button while there is an active upload
2. show file upload related error messages in snackbars
=> Improved File Manager UI

packages/validation/__tests__/url.test.js, packages/validation/src/validators/url.js
We want to be able to validate relative URLs, like eg. `"/relative/url?this=is"`.
Added `allowRelative` option to the `url` validator. You can use it like so:
```
await validation.validate("/relative/url?this=is", "url:allowRelative");
```
Unit test.
N/A
=> Added "allowRelative" option for the `url` validator

packages/app-i18n/src/admin/components/I18NInput.js, packages/app-i18n/src/admin/plugins/richTextEditor/link/LinkDialog.js
For specific use cases, users could decide to not-show the translate icon in the `I18NInput` component and also to define custom rendering. E.g. they could create a custom icon that will trigger the opening of the translations overlay.
Added `showTranslateIcon` prop on the `I18NInput` component. Users can also pass a function as the child of the `I18NInput` component, in order to define their own custom render.
N/A
=> I18NInput component - added ability to toggle visibility of the translate icon and define custom render

packages/app-page-builder/src/render/components/Slate.js
In PageBuilder, SlateEditor component throws an error if `props.value` is `undefined`. 
Pass a default `{}` to `Value.fromJSON` which would throw otherwise.
Manually.
=> Handle undefined value in SlateEditor component.

packages/api-page-builder/package.json, packages/api-page-builder/src/plugins/models/pbPage/contentField.js
When Page Editor saves page content, it returns images with IDs instead of data objects.
Make a deep clone of the current attribute values before applying modifiers that create the storage value, as we don't want to modify the attribute value itself.
Manually.
=> When creating storage value, do not modify current attribute value.

components/serverless-apollo-gateway/package.json, components/serverless-apollo-gateway/serverless.js, components/serverless-apollo-service/serverless.js, components/serverless-aws-api-gateway/package.json, components/serverless-aws-api-gateway/serverless.js, components/serverless-aws-cognito-user-pool/serverless.js, components/serverless-files/utils/configureS3Bucket.js, components/serverless-page-builder/serverless.js, packages/cli/cli.js, packages/cli/sls/execute.js, packages/cli/sls/template/serverless.js, packages/cli/sls/template/utils.js
This PR closes #608, closes #607. 
You can now run deploy of only the selected aliases:
`webiny deploy-api --alias i18n --alias security --debug`
Watching is not yet implemented.
=> Add support for selective component deploy and improve debug output

packages/cli/cli.js, packages/cli/package.json
This PR adds the `update-notifier` package which will notify users when a new CLI version is available.
=> Notify users a new CLI version is available.

components/serverless-files/functions/downloadFile/handler.js
It seems that the current `MAX_RETURN_CONTENT_LENGTH` value, located in `downloadFile` function, is too small. 
This is used upon serving files, to determine whether the file content should be directly returned to the API Gateway, or we should issue a 301 redirect. The previous value was `6000000`, which is equal to `5.72MB`, and in one particular case, although the max size of returned content by a Lambda function must be smaller than 6MB, returning an image of `5.13MB` caused issues for some reason.
`LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413.`
I set a new value, `5000000`, which is equal to `4.77MB`. Tested the case explained above, it works.
=> Adjusted the maximum file size that can be directly returned from the file download Lambda

packages/app-page-builder/src/editor/plugins/elementSettings/components/PMSettings.js, packages/ui/src/Tabs/Tabs.js
Fixes #621 
After searching RMWC for issues, I found this one [#524](https://github.com/jamesmfriedman/rmwc/issues/524).
Looks like this is a [bug in material-components-web](https://github.com/material-components/material-components-web/issues/5296) (not 100% sure), but to get around this issue I forced re-render of Tab contents when tabs are being switched. It's not optimal, but it works. When the Material team releases an official fix, we'll test and see if this hack of mine will be necessary.
Manually.
=> PageBuilder settings sliders

packages/api-security/src/plugins/security.js, packages/app-i18n/.babelrc, packages/app-i18n/package.json, packages/app-i18n/src/admin/components/I18NInput.js, packages/app-i18n/src/contexts/I18N/I18NContext.js, packages/app-security/src/components/createAuthLink.js
`invalid signature` can happen when user switches to another Webiny project, because the other project contains a different JWT Token secret. The main problem is that the admin UI just crashes, with a not very informative error message.
Updated the `createAuthLink` handler - now it read errors not only from the `code`, but also from the `extensions.exception.code` key. 
I also updated the `I18NContext.js` - we're now getting the `getI18NInformation` data using `lodash.get`, and not directly. This was needed because this part of code would cause errors, when an error is present on the backend.
Fixes #584 
N/A
=> Log out users on invalid signature security error

packages/i18n/__tests__/modifiers.test.js
Running `yarn test` fails because of a set of bad `i18n` lib's tests.
Fix relevant `i18n` lib's tests.
Unit tests.
N/A
=> Fix I18N broken tests

packages/app-admin/src/components/FileManager/FileDetails.js
Fixes #637 
In the File Manager, we used `useConfirmationDialog` hook, which only works if the dialog plugin (`packages/app-admin/src/plugins/Dialog/index.js`) was registered in the current layout, which isn't the case for Page Builder. Because of this, using this hook won't work.
I replaced `useConfirmationDialog` hook with a regular `ConfirmationDialog` component. Not only this fixes the reported issue, but it also makes the File Manager more modular because you don't have to think about the dialog plugin that needs to be registered in the layout. The solution will ensure the dialog is always shown.
N/A
=> File Manager: fix delete files action (not working in Page Builder)

examples/api/serverless.yml
Resizing images to 2500px (which is the maximum value) can last more than 10 seconds, causing the image transformer Lambda to time out, and the resized image never to be created.
I changed the timeout to 30seconds, and also increased the amount of memory, from 1024 to 1600.
Manual testing, with the image that caused the issue, it works now.
=> Image resizing not working for larger images (timeout)

packages/app-admin/src/plugins/GlobalSearch/SearchBar.js
Fixes #646.
It seems there's a bug in the `is-hotkey` lib - when I press the letter "n" on my keyboard, it also assumes that the `NumpadDivide` key was pressed. Not sure why (checked in few places in code). For now, I just removed this shortcut, we'll see in the future if we'll need to bring this hotkey back.
=> Remove "NumpadDivide" shortcut - doesn't work

packages/app-page-builder/src/editor/plugins/toolbar/onboarding/Onboarding.tsx
Closes #667
I've created a background div that's clickable and closes the Guide.
Locally by running the `admin` app, reproducing the issue and fixing it.
=> feat: Clicking outside the 'Get Started Guide' modal now exits the guide

packages/cli/create/index.js, packages/cli/create/template/example.env.json
#679 
I split the updating of `/api/.env.json` and `/.env.json`. The [DATABASE] will now be replaced in `/.env.json`
By placing a `[DATABASE]` string in `packages\cli\create\template\example.env.json` and running `webiny create test-project`. This produced an `.env.json` file with a correct value (ie: webiny-123456789) `[DATABASE]` value.
=> fix: Database is now replaced in /.env.json instead of /api/.env.json

packages/app-page-builder/src/render/plugins/slate/link/index.tsx
#683 
The external links have been fixed by using `<a>` instead of `<Link>` elements. It seems like Link elements haven't been designed to allow "routing" to external URLs (https://github.com/ReactTraining/react-router/issues/1147), so I've just scrapped them. They still look the same to me now on the site.
I've unzipped `webiny\components\serverless-page-builder\installation\page_builder_installation_files.zip` and replaced 
`https://docs.webiny.com/docs/developer-tutorials/local-setup`
`https://docs.webiny.com/docs/cms-guides/get-started-webiny-administration` 
with  
`https://docs.webiny.com/docs/webiny/introduction/`
`https://docs.webiny.com/docs/get-started/quick-start`.
By running `site` app locally and clicking the new `<a>` elements.
=> fix: All external links now work. Two broken links have been replaced

packages/api-page-builder/src/plugins/graphql/installResolver/install.ts
#689 
In the finalization step (step 5) of the Page Builder installation process, we just initiate `GET` requests to all pages that were created.
=> Generate initial SSR and cache for default pages in the PB installation process

cypress.json, cypress/fixtures/example.json, cypress/integration/admin/formBuilder/forms/createForm.spec.js, cypress/integration/admin/formBuilder/forms/pageBuilderElement.spec.js, packages/app-form-builder/src/admin/views/Forms/Forms.tsx, packages/app-form-builder/src/admin/views/Forms/FormsDataList.tsx, packages/app-form-builder/src/admin/views/Forms/NewFormDialog.tsx, packages/app-form-builder/src/editor/plugins/defaultBar/BackButton.tsx, packages/app-form-builder/src/editor/plugins/defaultBar/Name/Name.tsx, packages/app-form-builder/src/page-builder/admin/plugins/components/FormElementAdvancedSettings.tsx, packages/app-form-builder/src/page-builder/admin/plugins/components/graphql.js, packages/app-page-builder/src/editor/plugins/blockEditing/AddContent.tsx, packages/ui/src/Button/Button.tsx
#678
First, I fixed another bug here - if a user created a new form (which redirects him to the form editor) and then returned back to the forms view, the new form would not be visible in the list of forms. That's why we added the following  at `packages/app-form-builder/src/admin/views/Forms/NewFormDialog.tsx:58`:
```
refetchQueries: ["FormsListForms"],
awaitRefetchQueries: true
```
Regarding the initial issue...
I added `fetchPolicy="network-only"` in the `packages/app-form-builder/src/admin/views/Forms/NewFormDialog.tsx:57`, because the just added `refetchQueries: ["FormsListForms"]` in the `packages/app-form-builder/src/admin/views/Forms/NewFormDialog.tsx:57` had no effect, or in other words, when re-opening the page builder and then form element's settings, the list of forms would …
=> Make sure new forms are visible in page builder (without refreshing the page)

packages/commodo-fields-storage-db-proxy/src/DbProxyDriver.ts
#682 
The following message will be returned from the API, if the database connection wasn't successfully established:
> Could not connect to MongoDB server, make sure the connection string is correct and that the database server allows outside connections. Check https://docs.webiny.com/docs/get-started/quick-start#3-setup-database-connection for more information.
This will make debugging connection-related issues easier for new developers.
=> fix: show a more friendly database connection error message

examples/apps/serverless.yml, package.json, packages/api-page-builder/src/plugins/graphql/installResolver/install.ts, packages/api-page-builder/src/plugins/models.ts, packages/api-page-builder/src/plugins/useSsrCacheTags.ts, packages/api-page-builder/src/types.ts, packages/http-handler-ssr/src/Client.ts
If a user visits his site without installing everything from the Admin, he will receive the "Installation Incomplete" error (with the link to the Admin of course).
The problem is, this generic page gets cached on the CDN, and after the installation has finished, this page would still be shown to the user.
### Solution
Once the PB installation has finished successfully, we trigger a cache invalidation request. This way, users will see the correct page, once the CDN cache has been cleared.
=> fix: invalidate site cache on successful installation

packages/commodo-fields-storage-db-proxy/src/DbProxyDriver.ts
When trying to establish a MongoDB connection with incorrect connection params, a few times, I've also received `MongoNetworkError` as the connection error type. In that case, we also want a nice error message (with the link to the docs) to be shown. Currently, we were only doing that when the error was type of `MongoServerSelectionError`.
Added `MongoNetworkError` to the array of all connection-related errors.
N/A
=> fix: add "MongoNetworkError" to the list of connection errors

packages/http-handler/src/create.ts, packages/http-handler/src/types.ts
I changed the type of the before/after handler plugins in the `http-handler` function:
- ~before-handle~ `before-handler`
- ~after-handle~ `after-handler`
N/A
=> fix: change the name of the before/after `http-handler` plugins

components/serverless-aws-cloudfront/serverless.js, components/serverless-aws-cloudfront/utils/setCdnDistributionForwardedHeader.js, components/serverless-aws-cloudfront/utils/unsetCdnDistributionForwardedHeader.js, examples/apps/serverless.yml, packages/cli/create/template/apps/serverless.yml, packages/http-handler-ssr/src/models/ssrCache.model.ts, packages/http-handler-ssr/src/ssrCacheApi.ts, packages/http-handler-ssr/src/ssrServe.ts
#708 
The problem that the user experienced here was related to the inproper cache invalidation. Initially, we would flush the CDN cache on every successful deployment, but not the SSR HTML in the database. 
So, after the deploy has finished, user would visit the site, his request would reach the `Site` Lambda function (because CDN has been flushed), and there, we would just return the same old SSR HTML back to the CDN / to the user.
From now on, on each deploy of CDN, we will generate a unique `deploymendId` and make the CDN send it via custom headers (`X-Cdn-Deployment-Id`). 
So, every time a request from the CDN arrives to the `Site` Lambda function, this deployment ID will be present in the invocation payload (in the `headers` key).
With this, we can detect a new deployment, or in …
=> fix: on new deployments, consider existing SSR HTML as stale

packages/http-handler/src/create.ts, packages/http-handler/src/types.ts
By default, if an error was thrown in the `Site` Lambda function (by one of the registered handlers - `examples/apps/site/handler/handler.js`), we would show the default error page, which wasn't customizable.
Ideally, users might want to customize this page or completely hide everything.
If an `error-handler` plugin was registered, it will be used to handle the thrown error. Otherwise, a generic error page will be shown.
N/A
=> feat: enable registration of error-handler plugin

packages/app-page-builder/src/editor/plugins/slate/italic/index.tsx, packages/app-page-builder/src/editor/plugins/slate/scroll/index.ts, packages/app-page-builder/src/editor/plugins/slate/underline/index.tsx
Fixes #716 
During migration to TS, I accidentally messed up Slate plugin signature on `onKeyDown` plugins. The solution was to restore the plugin signature for the corresponding `v0.42` version of `slate`.
Manually.
=> fix: restore slate v0.42 onKeyDown plugin signature

packages/app-page-builder/src/editor/plugins/elements/pagesList/index.tsx
Fixes #715 
There was a mismatch in component naming between `pb-editor-page-element-pages-list` and the actual component plugin. Now we use the `componentName` property of the plugin instead of its name.
Manual testing
=> fix: synchronize pageList component name with element plugin

packages/cli/cli.js, packages/cli/create/index.js, packages/cli/package.json, packages/cli/sls/deploy.js, packages/cli/sls/disableTracking.js, packages/cli/sls/enableTracking.js, packages/cli/sls/execute.js, packages/cli/sls/template/serverless.js, packages/cli/sls/template/utils.js, packages/http-handler-ssr/src/index.ts, packages/tracking/index.js, packages/tracking/package.json
The Webiny CLI internally tracks the user's usage. This exists because we want to have information about potential problems that the users might experience, and to make the DX as great as possible.
Note: this is clearly explained while the CLI is being used, and users can also completely disable tracking if they want, by running the `webiny disable-tracking`.
With this PR, we added tracking of the following CLI events:
- create_project_start
- create_project_end
- apps_deploy_start
- apps_deploy_end
- api_deploy_start
- api_deploy_end
- tracking-disabled
These events will give us an even better understanding of the experience our users are having.
=> Improve CLI usage tracking

packages/app-page-builder/src/editor/components/Element.tsx, packages/app-page-builder/src/editor/plugins/elements/row/Row.tsx, packages/app-page-builder/src/render/components/Element.tsx, packages/app-page-builder/src/utils/tryRenderingPlugin.tsx
#686 
Wrapped the two `Element.tsx` components inside Error Boundaries.
The `Render` `Element ` was tested by opening up the Pages. Here we clearly see an `Element` component which I've tested by intentionally throwing an error inside the Error Boundary.
=> Handle PB Element plugin errors during render

scripts/setupRepo.js
The hint when you run `yarn setup-repo` is wrong because the mongoDB connection string is in examples/.env.json, not examples/api/.env.json
I changed the hint about path to .env.json that point to mongoDB connection
run `yarn setup-repo`
=> change hint to examples/.env.json when running setup-repo

cypress/integration/admin/pageBuilder/menus/pagesListMenuItemType.spec.js, packages/api-page-builder/src/plugins/graphql/Page.ts, packages/api-page-builder/src/plugins/graphql/menuResolvers/prepareMenuItems.ts, packages/app-admin/src/components/SimpleForm/SimpleForm.tsx, packages/app-page-builder-theme/src/components/DesktopHeader.tsx, packages/app-page-builder-theme/src/components/Header.tsx, packages/app-page-builder-theme/src/components/MobileHeader.tsx, packages/app-page-builder/src/admin/views/Menus/MenusForm.tsx, packages/app-page-builder/src/admin/views/Menus/MenusForm/MenuItems/MenuItemRenderer.tsx
#731 
A couple of issues here.
First, the GraphQL query would not return the pages that need to be shown in the drop-down menu. This is because the modifier name was incorrect (`packages/api-page-builder/src/plugins/graphql/menuResolvers/prepareMenuItems.ts:112`). But even if it was correct, the code in there would still not work, had some refactor leftovers there as well.
Secondly, @Pavel910 also noticed the tags search input didn't work. I inspected that and found an error in the GraphQL resolver (`packages/api-page-builder/src/plugins/graphql/Page.ts`), so that was taken care of too.
Added Cypress tests that check if the "pages list" menu item type is working on the public-facing site. And to make sure the tags search is working as expected, I've used `error` and `not-found` tags when …
=> fix: tags search & "Pages List" menu item site rendering

cypress.json, cypress/integration/admin/security/roles/createGroup.spec.js, cypress/integration/admin/security/roles/createRole.spec.js, packages/api-form-builder/src/plugins/graphql.ts, packages/api-page-builder/src/plugins/graphql.ts, packages/api-security/src/plugins/graphql.ts, packages/api-security/src/scopes.ts, packages/app-form-builder/src/admin/plugins/index.ts, packages/app-form-builder/src/admin/plugins/scopesList.ts, packages/app-i18n/src/admin/plugins/index.ts, packages/app-i18n/src/admin/plugins/scopesList.ts, packages/app-page-builder/src/admin/plugins/index.ts, packages/app-page-builder/src/admin/plugins/scopesList.ts, packages/app-security/src/admin/components/ScopesMultiAutoComplete.tsx, packages/app-security/src/admin/components/index.ts, packages/app-security/src/admin/plugins/index.ts, packages/app-security/src/admin/plugins/scopesList.ts, packages/app-security/src/admin/views/Groups/Groups.tsx, packages/app-security/src/admin/views/Groups/GroupsDataList.tsx, packages/app-security/src/admin/views/Roles/Roles.tsx, packages/app-security/src/admin/views/Roles/RolesDataList.tsx, packages/app-security/src/admin/views/Roles/RolesForm.tsx, packages/app-security/src/admin/views/Roles/graphql.ts, packages/app-security/src/types.ts, packages/ui/src/AutoComplete/MultiAutoComplete.tsx
#729 
There are a couple of things this PR introduces.
1. First and foremost, users can finally get a list of all available security scopes in the system, in the Roles form. Users just have to register the app plugin with the type `security-scopes-list`, and their custom scope will be shown in the list. Default apps already are doing this out-of-the-box. For custom development, users will have to register this on their own (obviously).
2. Secondly, the scopes selection multi autocomplete was visually improved. Users can now see not only the meaningless scope (e.g. `fb:forms:crud`), but also its title and description. It will be more informative for the user. Check the sshot at the bottom.
3. I also removed some of the scopes-related functionality on the API side, since it's not needed …
=> feat: improved scopes selection auto-complete component

cypress/integration/admin/pageBuilder/menus/pagesListMenuItemType.spec.js, cypress/integration/admin/settings/siteRefresh.spec.js, cypress/support/commands.js, cypress/support/index.js, cypress/support/visitAndReloadOnceInvalidated/index.js, packages/api-page-builder/src/plugins/useSsrCacheTags.ts, packages/app-page-builder-theme/src/components/Footer.tsx, packages/app-page-builder/src/site/components/Page/Page.tsx
#727 
In a nutshell, the solution was simple. Every time changes to the page builder settings are made, we invalidate SSR cache (`packages/api-page-builder/src/plugins/useSsrCacheTags.ts:81`). 
The thing that was tricky was finding a way to invalidate all Page Builder pages. We don't want to necessarily invalidate ALL SSR HTML cache entries (this was the initial idea, discussed with @Fsalker). We just want to invalidate SSR HTML entries for URLs on which Page Builder pages are being rendered.
To solve this, I added a simple `pb-page` `ssr-cache` tag (`packages/app-page-builder/src/site/components/Page/Page.tsx:35`).
I'm closing @Fsalker's PR because this one also includes a couple of other features/fixes, and because it'll be faster this way.
We had a bug in the …
=> CDN cache is now invalidated properly upon updating Page Builder settings

packages/app-page-builder/src/site/plugins/linkPreload.ts
One of our users had a page that had an empty link in it (`href` attribute wasn't defined). 
Because of this, the `react-router-on-link-pb` plugin (`packages/app-page-builder/src/site/plugins/linkPreload.ts`) would throw an error, because it was using the `startsWith` function on a value that wasn't a string.
We now check if the passed `link` argument is actually a string.
=> Page Builder - fixed link preloading error

scripts/cz-adapter/index.js
Add config with breaklineChar for buildCommit function
https://github.com/webiny/webiny-js/issues/751
Add `breaklineChar` option in config. However we might want to use https://github.com/ds300/patch-package to fix this in library
I've been able to commit with the help of `yarn commit`
=> fix: 🐛  Commitizen error

packages/app-form-builder/src/admin/plugins/formDetails/formSubmissions/FormSubmissionsOverview.tsx, packages/ui/.storybook/webpack.config.js, packages/ui/src/Section/README.md, packages/ui/src/Section/Section.stories.tsx, packages/ui/src/Section/index.tsx
None, but it helps #762 and #695.
I had to employ a "Section" component in order to display the Personal Access Tokens.
I've moved the former `Block` component used in `packages/app-form-builder/src/admin/plugins/formDetails/formSubmissions/FormSubmissionsOverview.tsx` into the new `webiny/ui/Section` component.
I've run `admin` app locally and Form Builder looks the same when selecting a Form & displaying the "Overview" section.
=> Fixed Storybook local deployment & Added 'Section' component

packages/api-page-builder/src/plugins/useSsrCacheTags.ts
#757 
If the page that was published is marked as site's homepage, then we also invalidate the root path ("/") of the site.
N/A
=> SSR is now invalidated correctly when publishing site's homepage.

packages/app-page-builder/src/admin/utils/createElementPlugin.tsx
[#787](https://github.com/webiny/webiny-js/issues/787) 
I changed the type of getplugin as Adrian says in his issue
I tested in my deployed apps
The result
=> Page Builder: Saved page elements are now correctly shown in the page elements menu.

cypress/integration/admin/pageBuilder/pages/previewPage.spec.js, package.json, packages/app-page-builder/__tests__/getPagePreviewUrl.test.js, packages/app-page-builder/src/admin/hooks/usePageBuilderSettings/getPagePreviewUrl.ts, packages/app-page-builder/src/admin/hooks/usePageBuilderSettings/usePageBuilderSettings.ts, packages/app-page-builder/src/editor/plugins/defaultBar/components/PageOptionsMenu.tsx, packages/app-page-builder/src/editor/plugins/defaultBar/components/PreviewPageButton.tsx, packages/ui/src/Menu/Menu.tsx
Using `ts` as a way to ensure pages are not returned from the CDN cache was a bad idea. 
Yeah, it would work if the user would click on the `Preview` link all the time, but he's not. He would click on it just once, and after that, he would continue by refreshing the page, which would return the same cached page, and never the new one.
Ditched the idea, and added support for `?ssr-no-cache` query param. Every time this is present in the requested URL, SSR will be generated from scratch, and no cache will be involved.
Cypress test.
N/A
=> Previewing pages is now working as expected

cypress/integration/admin/pageBuilder/elements/pagesList.spec.js, packages/app-page-builder/src/editor/components/Slate/Slate.tsx
Clicking on the "link" icon in the Page Builder editor would bring up the link dialog, which would cause a "blur" event on the text, and a GraphQL update mutation to be sent. Then, when you would press the Save button in the dialog, the change would not save, because blur event already happened upon showing the dialog.
Both Irregularities mentioned above were taken care of.
I really wanted to test this, but it's gonna have to wait.
N/A
=> Page Builder - fixed saving of links (Slate editor)

packages/app-admin/src/components/FileManager/File.tsx
Show `infoIcon` on image hover
[UI improvement] The "i" icon that opens picture properties in File Manager is not obvious
https://github.com/webiny/webiny-js/issues/756
Instead of changing `infoIcon` color to theme-secondary on hovering over the icon itself,
now the `infoIcon` will be visible when hovering over the image
1. Visit the admin app and navigate to the pages section
2. Edit a page and select an image block
3. In the File Manager, hover over an image and `InfoIcon` i.e "i" icon that shows picture properties in File Manager will appear
https://www.loom.com/share/fe2471e87ce54bdfa5d11f545ea044ef
=> Fixed the styles for the "i" icon in the File Manager.

packages/app-admin/src/plugins/UserMenu/UserMenu.tsx
Issue #810 
Headless CMS - User menu not opening anymore
Use an `HTML` element instead of `React.Fragment`
We can also revert the change and use `menu-handle`
Manually, by following these steps:
1. Visit the admin app
2. Click on user avatar present at top RHS corner
3. User is able to see the user menu 
https://www.loom.com/share/61b351260bbc4bc8865ec8bffaaef824
=> Fix: Headless CMS - User menu not opening anymore

packages/app-page-builder/src/editor/plugins/elements/button/ButtonSettings.tsx, packages/app-page-builder/src/editor/plugins/elements/icon/IconSettings.tsx, packages/app-page-builder/src/editor/plugins/elements/icon/index.tsx, packages/app-page-builder/src/editor/plugins/elements/icon/utils.ts
Issue #761 
Page Builder - "Icon" page element not working
My solution has two parts:
1. Fix `getSvg` function by add missing width prop to `getSvg` function and add default value for `props` arg
2. Improve the functionality of changing width prop in Icon Picker by removing 50 passed to value and adding 50 as placeholder text to input
manually tested my solution using the following steps:
1. Login into the Admin app and select any page to edit.
2. Inside page editor, use the LHS menu to insert an icon element into the page.
3. The icon is visible in preview and also applied changes to Icon properties like `color` and `width` 
are reflected in the preview
Here is the result after applying the above-mentioned solution
https://www.loom.com/share/153230b1245546b8b638e57e2e4433b8
=> Fix: Page Builder - "Icon" page element not working

packages/app-page-builder/src/editor/components/OEmbed.tsx
We've encountered an issue where opening the "Get Started" page generated by default, when initially creating the app, was crashing because of an Oembed bug.
This issue was fixed so quickly that I skipped writing a separate issue for it 😎
For some reason, when `skip` is set to `true`, `onComplete` function will still be executed. This caused the app to break.
So, I've added a return statement to prevent this.
Ran admin app locally.
=> fix: prevent crash & run prettier

packages/api-headless-cms/src/handler/plugins/graphqlFields/datetime.ts, packages/api-headless-cms/src/handler/plugins/modelFields/datetime.ts, packages/app-headless-cms/src/admin/components/ContentModelForm/ContentModelFormRender/fields/DateTimeWithTimezone.tsx, packages/app-headless-cms/src/admin/components/ContentModelForm/ContentModelFormRender/fields/DateTimeWithoutTimezone.tsx, packages/app-headless-cms/src/admin/components/ContentModelForm/ContentModelFormRender/fields/Select.tsx, packages/app-headless-cms/src/admin/components/ContentModelForm/ContentModelFormRender/fields/Time.tsx, packages/app-headless-cms/src/admin/components/ContentModelForm/ContentModelFormRender/fields/utils.ts, packages/app-headless-cms/src/admin/components/ContentModelForm/ContentModelFormRender/index.tsx, packages/app-headless-cms/src/admin/plugins/fields/dateTime.tsx
Issue #831 
Headless CMS - finish date field
Following the solution suggested in the issue #831 
Finish up the UI for date field in headless CMS
Manually, by creating a content model with
**date time with timezone**
**date time without timezone**
**time**
**date**
=> Fix: Headless CMS - finish date field

packages/api-headless-cms/src/handler/plugins/utils/createEnvironmentBase.ts
when run yarn setup-repo, there is an error:
@webiny/api-headless-cms: src/handler/plugins/utils/createEnvironmentBase.ts(6,20): error TS2339: Property 'query' does not exist on type '{}'.
assign the returnArgs to type any
run yarn setup-repo successfully without error
=> fix: 🐛  fix the query in return args

packages/app-admin/src/components/FileManager/getFileTypePlugin.ts
No related issue on Github
add missing `admin` prefix in plugin name when fetching plugins for that type
Manually, by following these steps:
- Visit the admin app and try selecting user profile avatar
- When file manager loads up, select one image
- User should be able to see the image preview
https://www.loom.com/share/cb6d0c927ee34444b2db082a4b2ac728
=> fix: 🐛  update `plugin` name

packages/app-headless-cms/src/admin/components/ContentModelForm/ContentFormRender.tsx
Issue #874 
Headless CMS - cannot erase the first character in the input field
Don't create new value entry for the empty string
Manually, by following these steps:
- Visit the admin app and create a content model entry with `text` field
- Try adding some text and then try erasing it
- User should be able to erase all of the text including the first character
https://www.loom.com/share/51871c4f962a42f18292c5dadc85f2db
=> Fix: Headless CMS - cannot erase first character in input field

packages/app-headless-cms/src/admin/plugins/fields/dateTime.tsx
Closes #893
The problem occurred in cases where the user didn't select a date/time format in the field settings dialog.
Although it seems like the format is selected, because there is a value in the input, the actual data in the state was empty.
=> Fixed a crash that occurred upon adding the Date/Time field

packages/app-i18n/package.json, packages/app-i18n/src/admin/components/I18NInputLocalesOverlay.tsx
Closes #871 
The `I18NInputLocalesOverlay` component being present at a higher z-index was not being closed alone, but also closed its parent component `I18NInput` before.
This bug was fixed by isolating the child component via stopping the event propagation and then closing only the dialog of the child component. React Hotkeyz' `useHotkeys` hook was super useful, as the keys object came with properties embedded with the event object.
N/A
=> fix: 🐛  Fixed bug of #871 pressing Esc closes the edit field dialog

packages/app-headless-cms/src/admin/components/ContentModelForm/graphql.ts, packages/app-headless-cms/src/admin/plugins/contentDetails/contentForm/ContentForm.tsx, packages/app-headless-cms/src/admin/views/Content/Content.tsx, packages/app/src/hooks/useDataList/useDataList.ts
Closes #888 
Instead of doing plain refreshes of the actual list, we are manually updating the Apollo cache. Besides the actual fix described in the issue, we also get the bonus of not making requests to the backend and a faster UI.
=> Headless CMS - entries list is now being refreshed properly

packages/api-headless-cms/__tests__/accessTokensAuthentication.test.js, packages/api-headless-cms/src/content/plugins/index.ts, packages/api-headless-cms/src/plugins/models/accessToken.model.ts, packages/app-headless-cms/src/admin/views/AccessTokens/AccessTokensForm.tsx, packages/ui/src/Button/CopyButton/CopyButton.tsx
-fixed AT creation when you don't specify a description
-added a nice Snackbar message to the ButtonCopy UI component
-`access-token` header is now `authorization` / `Authorization`
See the code, it's pretty small. I've just implemented/fixed the stuff...
Locally
=> Access Tokens Improvements v2

packages/app-page-builder/src/admin/views/Pages/EditorStyled.ts
Make image that accompanies `Loading Editor...` text stay at the screen after animation finishes
https://github.com/webiny/webiny-js/issues/798
Removed animation step that made image disappear from the screen. 
Manually at localhost (https://cl.ly/88b9bf308042)
=> feat: ✨  make PB Editor loader image stay at screen after animation

packages/app-admin/src/plugins/UserMenu/UserMenu.tsx
Makes the entire TopActionBarItem as the Menu handle instead of just the Avatar
BREAKING CHANGE:
N.A.
Fixes #773 
This PR makes sure that both the User avatar as well as white ripple outside the avatar are clickable and open the user menu.
Tested locally and visually
N.A.
=> fix: 🐛  make circle area outside user-menu clickable

scripts/cz-adapter/index.js
Closes #974 
Added a missing input for scope.
Manually, by running `yarn commit`.
=> chore(cz-adapter): add an input for commit scope

packages/api-headless-cms/__tests__/lockedFields.test.js, packages/api-headless-cms/__tests__/mocks/unlockingFields.js, packages/api-headless-cms/__tests__/removeFieldPresentInIndexes.test.js, packages/api-headless-cms/__tests__/unlockingFields.test.js, packages/api-headless-cms/src/content/plugins/models/contentModel.model.ts, packages/api-headless-cms/src/content/plugins/utils/createDataModel.ts
Closes #943
Closes #944 
Every time a model is deleted, a count of all entries will be performed. If `0`, then we unlock all fields.
Jest.
N/A
=> Headless CMS - automatically unlock all fields on entries removal

packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/DateTimeWithTimezone.tsx, packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/DateTimeWithoutTimezone.tsx, packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/Input.tsx, packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/Time.tsx, packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/dateTimeField.tsx, packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/dateTimeFields.tsx, packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/index.ts, packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/utils.tsx, packages/app-headless-cms/src/admin/plugins/fields/dateTime.tsx, packages/ui/src/Input/Input.tsx
closes #914 
#914 
Headless CMS - "multipleValues" renderer for Date/Time field 
Use `DynamicListMultipleValues` component 
https://www.loom.com/share/ed8b97db76e8426ba86af1aa70e4572f
=> Headless CMS - "multipleValues" renderer for Date/Time field

packages/app-i18n/src/admin/components/RichTextEditor/RichTextEditor.tsx
Closes #970 #933 
Headless CMS - Rich Text Editor Max Height
- Fix content getting too tall that toolbar hide due to scroll, by adding `height` property
- Add resizer so that the user can resize the editor if needed
Manually, via the Admin app
=> Fix: Headless CMS - Rich Text Editor Max Height

packages/app-page-builder/src/admin/hooks/usePageBuilderSettings/usePageBuilderSettings.ts, packages/app-page-builder/src/admin/plugins/settings/components/generalSettings/GeneralSettings.tsx
Closes #962 
update `pageBuilder` settings in the cache after `updateSettings` mutation in file
`packages/app-page-builder/src/admin/plugins/settings/components/generalSettings/GeneralSettings.tsx`
Manually, via the Admin app UI
https://www.loom.com/share/81a083db4f404e3cb725e4d0090c1016
=> Fix: Page Builder - updating domain in PB settings doesn't get immediately reflected in the rest of the app

packages/app-page-builder/src/editor/plugins/pageSettings/components/GeneralSettings.tsx
General settings in Page Builder Editor have a `snippet` field and for some reason it's still using the `outlined` prop, which changes the look and feel of the input. All other textareas are not using it.
Remove the `outlined` prop.
Manually
=> fix(app-page-builder): remove outlined prop

packages/api-headless-cms/__tests__/mocks/modelDeletionGqlFieldsHiding.js, packages/api-headless-cms/__tests__/mocks/preventIdsStartingWithNumbers.js, packages/api-headless-cms/__tests__/modelDeletionGqlFieldsHiding.test.js, packages/api-headless-cms/__tests__/preventIdsStartingWithNumbers.test.js, packages/api-headless-cms/__tests__/utils/useContentHandler.js, packages/api-headless-cms/__tests__/utils/useContentHandler/getData.js, packages/api-headless-cms/__tests__/utils/useContentHandler/graphql.js, packages/api-headless-cms/src/content/plugins/models/ContentModel/createFieldsModel.ts, packages/api-headless-cms/src/content/plugins/models/ContentModel/idValidation.ts, packages/api-headless-cms/src/content/plugins/models/contentModel.model.ts, packages/commodo-graphql/src/InvalidFieldsError.ts
Closes #887 
Closes #987
I added necessary validation on `fieldId` and `modelId` fields. 
While working on #887, I also discovered that validation errors are still not returned properly in GQL responses. While working on it, I also discovered [another issue in the Commodo library](https://github.com/webiny/commodo/issues/9). I documented it and hopefully, we'll be able to revisit it soon.
Schema refreshing is now triggered in the `afterDelete` in the `packages/api-headless-cms/src/content/plugins/models/contentModel.model.ts:92`
Jest.
N/A
=> Headless CMS - model and field IDs can only start with letters (a-z)

packages/app-headless-cms/src/admin/plugins/fieldRenderers/number/numberInputs.tsx
Closes #997 
Headless CMS - number field (multiple values) not working
Save value as a `number` instead of `string`
=> FIx- Headless CMS - number inputs field not working

packages/app-headless-cms/package.json, packages/app-headless-cms/src/admin/components/ContentModelEditor/Fields.tsx, packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/EditTab/EditFieldDialog/GeneralTab.tsx, packages/app-headless-cms/src/admin/plugins/fields/boolean.tsx, packages/app-headless-cms/src/admin/plugins/fields/dateTime.tsx, packages/app-headless-cms/src/admin/plugins/fields/file.tsx, packages/app-headless-cms/src/admin/plugins/fields/longText.tsx, packages/app-headless-cms/src/admin/plugins/fields/number.tsx, packages/app-headless-cms/src/admin/plugins/fields/ref.tsx, packages/app-headless-cms/src/admin/plugins/fields/richText.tsx, packages/app-headless-cms/src/admin/plugins/fields/text.tsx, packages/app-headless-cms/src/types.ts
Closes #967 
I think having a separate field for Image and Image gallery is not necessary.
Provide more context/clarity to users by:
1. Adding a description for each field in the editor.
2. Reworded multi values toggle label such that it will be more clear to the user what is means. something like use as a list of <field type> i.e use as a list of file
Manually, by the Admin app UI
=> Headless CMS - add field description

packages/api-headless-cms/__tests__/limitListContentEntries.test.js, packages/api-headless-cms/__tests__/mocks/limitListContentEntries.js, packages/api-headless-cms/src/content/plugins/utils/createFindParameters.ts, packages/api-headless-cms/src/content/plugins/utils/findEntries.ts
Closes #983 
Headless CMS - `limit` param in list content model query not working 
- Add `model` in query
- Scale `limit` by locales for MANAGE API
Manually, using GraphQL playground for `manage` API
=> Fix: `limit` param in list content model query not working

packages/app-headless-cms/src/admin/components/ContentModelForm/ContentFormRender.tsx, packages/app-headless-cms/src/admin/plugins/contentDetails/header/contentFormOptionsMenu/ContentFormOptionsMenu.tsx, packages/app-headless-cms/src/admin/plugins/contentDetails/header/index.tsx, packages/app-headless-cms/src/admin/plugins/contentDetails/header/saveAndPublishContent/SaveAndPublishContent.tsx, packages/app-headless-cms/src/admin/plugins/contentDetails/header/saveContent/SaveContent.tsx, packages/app-headless-cms/src/admin/plugins/index.ts
Closes #966 
Changes:
1. Now, we will no longer have the footer. The save button is now moved to the form header.
2. There is also a Save & Publish button right beside Save
3. The actions like Revision menu and delete content has been moved to the left side.
4. The Publish action has been removed because now we have Save & Publish
5. Form header is fixed and only the form's body is scrollable (if the content extend beyond the fixed height)
6. Move `delete` action in 3 dot menu
=> Feat: Headless CMS - add Save & Publish button

packages/app-security/src/admin/views/Account.tsx, packages/ui/src/Snackbar/index.ts
Sets the message to null on clicking close thus closing snackbar
Closes #766 
Please refer to #1010
=> fix(snackbar): fix close button in snackbar at account page

packages/app-form-builder/src/admin/plugins/formDetails/formSubmissions/FormSubmissionsList/FormSubmissionsList.tsx
Closes #1027
Remove `$` sign from the label
Manually
=> fix: remove unnecessary "$" sign in the label

packages/app-headless-cms/src/admin/plugins/fields/ref.tsx, packages/ui/src/AutoComplete/AutoComplete.tsx
Closes #1011 
Add a placement prop on `AutoComplete` with which we can switch the placement position of the dropdown menu
https://www.loom.com/share/89dbac07167f4bcc9fada2e93a519079
=> Fix: Headless CMS - edit field dialog - dropdown not visible

packages/app-i18n/src/admin/components/RichTextEditor/RichTextEditor.tsx
Closes #1013 #1014 
- Fix cannot focus on Rich Text Editor issue
- Use a fixed height instead of viewport responsive
https://www.loom.com/share/57d762de2dd7452a9379977ba876bb50
=> Fix: Headless CMS - cannot focus Rich Text Editor

packages/handler-ssr/src/cdnSsrCacheInvalidation.ts
I corrected the plugin type in `packages/handler-ssr/src/cdnSsrCacheInvalidation.ts:5` (changed `context` to `handler-context`). This plugin is responsible for issuing CDN invalidation requests.
N/A
=> Corrected plugin type

packages/create-webiny-project/init.js
Closes #1022 
Passed a context variable as well as a task variable
Ran a new project that automatically threw an error to ensure that task.skip code piece was run:
I got this output (see below)
=> fix(cwp): fix initialize git step so on error it runs task.skip

packages/api-headless-cms/__tests__/manageAPI/snapshots/product.js, packages/api-headless-cms/__tests__/mocks/contentModels.js, packages/api-headless-cms/__tests__/mocks/fields/refReferencedIn.js, packages/api-headless-cms/__tests__/readAPI/snapshots/product.js, packages/api-headless-cms/__tests__/refFieldReferencedIn.test.js, packages/api-headless-cms/__tests__/utils/useContentHandler/graphql.js, packages/api-headless-cms/src/content/plugins/index.ts, packages/api-headless-cms/src/content/plugins/modelFields/refField/addRefFieldHooks.ts, packages/api-headless-cms/src/content/plugins/models.ts, packages/api-headless-cms/src/types.ts
Closes #938 
Previously, you would be able to delete a content model, even if it was referenced by another one. This is no longer the case. In order to delete the referenced content model, you need to remove the "ref" fields first.
Jest.
N/A
=> Referenced models cannot be deleted anymore

packages/app-typeform/package.json, packages/app-typeform/src/admin/TypeFormEmbed.tsx, packages/app-typeform/src/admin/index.tsx
Closes #617 
```tsx
import { i18n } from "@webiny/app/i18n";
const t = i18n.ns("app-typeform/admin");
```
Now wrap strings into `t` template literal
Manually
=> feat: i18n support for typeform app using t template literal

packages/app-google-tag-manager/src/admin/components/GoogleTagManagerSettings.tsx, packages/app-google-tag-manager/src/admin/index.tsx
Closes #619 
```tsx
import { i18n } from "@webiny/app/i18n";
const t = i18n.ns("app-google-tag-manager/admin");
```
Now wrap strings into `t` template literal
Manually
=> feat: i18n support for app-google-tag-manager

packages/app-headless-cms/src/admin/plugins/fields/ref.tsx
Closes #1058 
Use `LIST_MENU_CONTENT_GROUPS_MODELS` query instead of `LIST_CONTENT_MODELS` inside `ref` field settings
Manually using the Admin app.
https://www.loom.com/share/ea0a7539318c4b33b83ef7236bc546cb
=> Fix: Headless CMS - must refresh the page in order to see my new model

packages/app-headless-cms/src/admin/plugins/fieldRenderers/index.ts, packages/app-headless-cms/src/admin/plugins/fieldRenderers/select.tsx
Relates to #1076
Feels a bit like too easy 👍  but I have added a `select` fieldRenderer based heavily on the radio button as per suggestion by @Pavel910.
To be honest I may need help with testing as I am new to using / contributing to the framework. I checked the select box appears in the edit content-model preview panel.
And `cms/content-models/manage` page
I did look to add unit and integration tests but it seems you folks have some integration ones but not around this part of the app, I felt adding integration tests to test the content models groups and models fell outside the scope of this PR.
=> feat: add select to fieldRenderers

packages/app-admin/src/plugins/Logo/Logo.tsx, packages/app-admin/src/plugins/Logo/index.tsx, packages/app-admin/src/plugins/Menu/Navigation/index.tsx, packages/app-admin/src/types.ts
One of the users noticed that there is no way of going back to the initial welcome screen in the Admin app. As suggested, we made the Webiny logos, located in the header bar and in the main menu, link to the welcome screen, so that it can be easily revisited.
=> Webiny logo now links to the welcome screen

packages/cwp-template-cms/template/api/resources.js, packages/cwp-template-full/template/api/resources.js, packages/cwp-template-full/template/apps/resources.js, sample-project/api/resources.js
For the DB Proxy Lambda function, which is handling everything database related (more information in [this](https://blog.webiny.com/using-aws-lambda-to-create-a-mongodb-connection-proxy-2bb53c4a0af4) blog post), we had the default Lambda function concurrency limit set to 15. Basically, this means that we can have 15 concurrent invocations of the DB Proxy Lambda function, which, as it turned out, is not hard to reach, even in local development. To prevent this, we decided to increase this value to 50, which will significantly help in preventing the concurrency limit to be reached again.
Note that the `concurrencyLimit` parameter can still be found in `api/resources.js` and `apps/resources.js` files. So, if further adjustments are needed, they can be made there.
N/A
=> The concurrency limit for the DB Proxy lambda function increased from 15 to 50

packages/app-admin/src/types.ts, packages/app-form-builder/src/admin/plugins/menus.tsx, packages/app-page-builder/src/admin/plugins/menus.tsx
In order to make the Admin app easier to use, we decided to remove the single "Content" section in the main menu, which held both Page Builder and Form Builder apps links. These apps now have their respective menu sections, like all other apps.
=> The "Content" section in the main menu is replaced with the "Page Builder" and "Form Builder" sections

packages/api-page-builder/src/plugins/models.ts, packages/api-page-builder/src/plugins/models/pbCategory.model.ts
Closes #1054
Catch page Categories with existing linked pages, so when attempting to delete a category with pages it will throw an error.
Not tested yet. Just a base for the code based on an [existing example](packages/api-headless-cms/src/content/plugins/models/contentModel.model.ts:81) has been added.
Much of its content doesn't apply to what is needed to be done.
Screen shot of existing example for reference:
=> fix: Page Builder - preventing category deletion with linked pages.

packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/IndexesTab/IndexesTab.tsx, packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/PreviewTab/PreviewTab.tsx, packages/app-page-builder-theme/src/styles/base.scss, packages/app-page-builder-theme/src/styles/variables.scss
Closes https://github.com/webiny/webiny-js/issues/953
There were a couple ways to fix this (I am not familiar with preferred standards), however I removed a collision the styled components were creating with enforced background colors that were still on the light theme but were redundant due to ` mdc-elevation--z${VALUE}` styles. For the rich text editor I updated the value for the variable when the page is within the `.dark-theme`. Was debating updating `--webiny-theme-color-surface` instead of removing the styled css declarations.
Manually (locally) checking before and after styles based on attached screens shots. Looked through the app also to see where else these styles may have been used.
=> Fix(CMS, Page Builder): Preview Background Color and Rich Text Color on Dark Theme

packages/app-headless-cms/src/admin/views/EnvironmentAliases/EnvironmentAliases.tsx, packages/app-headless-cms/src/admin/views/EnvironmentAliases/environmentAliasesUtils.ts, packages/app-headless-cms/src/admin/views/Environments/EnvironmentsDataList.tsx, typings/shared/index.d.ts
Closes #1114 
- add `refetchQueries` to delete operation
- add `updateCacheAfterCreate` as update on create operation
Manually using the Admin app.
https://www.loom.com/share/44e758172bfe41978a41b939aa27b241
=> Fix: Headless CMS - sync environments with aliases

jest.config.base.js, packages/cwp-template-cms/template/jest.config.base.js, packages/cwp-template-full/template/jest.config.base.js
When creating new projects with CWP, `yarn test` would stop working as soon as you added the 2nd package into the `api` folder. The error was happening because of an incorrect merge, happening in the `jest.config.base.js` config file.
I fixed the merge happening in the `jest.config.base.js` config file.
N/A
**Title**: Running Jest tests now works as expected
**Body**: We had a couple of reports of Jest tests not executing properly as soon as two or more custom packages are created (e.g. two Apollo GraphQL Services). This now works as expected, so you can continue writing your tests as usual and be confident that your app works as expected.
=> fix: prepend empty object when doing merge.recursive

packages/api-page-builder/src/plugins/graphql/menuResolvers/prepareMenuItems.ts, packages/api-page-builder/src/plugins/graphql/pageResolvers/getPublishedPage.ts, packages/api-page-builder/src/plugins/graphql/pageResolvers/listPages.ts, packages/api-page-builder/src/plugins/graphql/pageResolvers/listPublishedPages.ts, packages/api-page-builder/src/plugins/models.ts, packages/api-page-builder/src/plugins/models/pbPagesListPage.model.ts, packages/api-plugin-page-builder-resolvers-mongodb/src/index.ts, packages/api-settings-manager/src/client/SettingsManagerClient.ts
When printing out menus, on the backend, the default limit of `10` was applied to the `listPublishedPages` query, which would cause menus on the public website to not render completely when there were more than 10 pages to load.
I increased the limit to `200` (`packages/api-page-builder/src/plugins/graphql/menuResolvers/prepareMenuItems.ts`).
I noticed that even when we are just listing pages, we are loading the content for each page, which means loading the images as well. This is redundant, so I made a fragment Commodo model `PbPagesListPage`, that is used when listing pages. It's a simple model, without any hooks / advanced fields and behavior.
Although, while testing, I noticed more places ready to be optimized, a nice result can be seen while executing this basic pages list query: …
=> Page Builder - fixed Menus not being rendered completely

packages/app-page-builder/src/editor/plugins/elementSettings/bar/ElementSettingsBar.tsx, packages/app-page-builder/src/editor/utils.ts, packages/app-page-builder/src/types.ts
Add a way to load element settings to page element by defining element is `pb-editor-page-element-settings` plugin so that  a new settings plugin can also be applied to existing page elements 
Manually, by using page builder app UI
=> Feat: PB dynamic element settings plugin

packages/app-template-admin-full/src/index.tsx
Closes #1177
I just moved ```...(options.plugins || [])``` to the bottom of the array.
@Pavel910 Am I right, in that this works becuase the Array is itterated through accendently from the start to the end, with Options essentially overwriting previous data / value changes from the other plugins callbacks?
Will test this manually next.
None yet.
=> fix: Made options plugins effective

packages/app-admin/src/components/FileManager/FileDetails.tsx, packages/app-admin/src/components/FileManager/FileDetails/Tags.tsx
Closes #1180 
I redesigned the **tags** form - it looks like the above **name** form. Having the submit/cancel buttons will be more understandable for users and will prevent the problem in #1180 from happening.
=> File Manager - improved file tags form

package.json, packages/api-headless-cms/__tests__/manageAPI/snapshots/category.js, packages/api-headless-cms/__tests__/manageAPI/snapshots/product.js, packages/api-headless-cms/__tests__/manageAPI/snapshots/review.js, packages/api-headless-cms/__tests__/readAPI/snapshots/category.js, packages/api-headless-cms/__tests__/readAPI/snapshots/product.js, packages/api-headless-cms/__tests__/readAPI/snapshots/review.js, packages/api-headless-cms/src/content/plugins/schema/createManageSDL.ts, packages/api-headless-cms/src/content/plugins/schema/createReadSDL.ts
Using quotes in `model.description` make the CMS GraphQL server to crash.
Fix multi-line comment format in CMS GraphQL schema.
Manually, using the Admin app and GraphQL playground.
=> Fix: headless CMS model description

packages/api-headless-cms/__tests__/mocks/preventIdsWithWrongFormat.js, packages/api-headless-cms/__tests__/preventIdsWithWrongFormat.test.js, packages/api-headless-cms/src/content/plugins/models/ContentModel/createFieldsModel.ts, packages/api-headless-cms/src/content/plugins/models/ContentModel/idValidation.ts, packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/EditTab/EditFieldDialog/GeneralTab.tsx
Closes #1211 
Add proper field validation for the same both on App and API side.
Manually using the Admin app UI
=> Fix: CMS: Adding a field named `id` to the content model leads to a server crash

packages/cli-plugin-deploy-components/execute/Status.js
Closes #1219 
Exit `render` and `start` methods of Status class if `process.env.CI` is set.
Manually, by running a deploy with `process.env.CI` set to `true` (it can be any value, as long as the CI key is set).
=> fix(cli-plugin-deploy-components): disable status messages in CI

packages/app-security/src/admin/plugins/UserMenu/UserInfo.tsx
Closes #1196
Add the same CSS to the email address span that the user name header above already has.
Tested in Chrome and Safari only (are there any other relevant rendering engines now?). Just a quick visual check.
=> fix: email addresses with hyphens shouldn't wrap in the UserMenu

packages/project-utils/bundling/function/webpack.config.js
Closes #1230
Removed explicit mode setting, and relying on build in functionality: https://www.npmjs.com/package/webpackbar#fancy
In user mode (`yarn build`) the progress bar is still there.
In non user mode (`yarn lerna run build --concurrency 10  --stream`) the progress bar is hidden, and only text notifications are used.
=> fix: Project utils: disable webpack progressbar in non interactive teminal

packages/app-admin/src/plugins/init.tsx
Closes #1223
Checking the amount of actually rendered settings plugins. And if the list is empty, we return null.
Locally agains my codebase. Tested with no settings plugin, and with settings plugin which rendered null.
=> Feat: App Admin: hide settings group if empty

packages/app-admin/src/plugins/index.ts, packages/plugins/src/types.ts
Closes #1221
As described in the issue:
I've added a new type for the plugin collections, and used that to explicitly define the return type for the exported plugin collection.
Builded the d.ts files locally.
Before:
```typescript
/// <reference types="react" />
declare const _default: () => (import("../types").AdminLayoutComponentPlugin | import("../types").AdminFileManagerFileTypePlugin[] | import("../types").AdminInstallationPlugin | import("../types").AdminHeaderMiddlePlugin | import("../types").AdminHeaderRightPlugin | import("../types").AdminLayoutComponentPlugin[] | {
name: string;
type: any;
render(): JSX.Element;
} | (import("../types").ApiInformationDialogPlugin | import("../types").AdminHeaderLeftPlugin)[] | (import("../types").AdminHeaderLeftPlugin | …
```
=> Fix: App Admin: plugins export type fix

packages/project-utils/bundling/ssr/buildAppSSR.js
Closes #1218
Added the options as discussed with @Pavel910 
I'm using this solution for a few weeks now 😅 
**Title**: Customize your SSR build
**Content**: You can now customize your SSR build by providing paths to your app HTML file and app component factory. In most cases, you won't need it and Webiny defaults will work fine for you. But if you do find yourself in a situation where you need to tweak your HTML or app component - now you can do it. A shout out goes to [Latotty](https://github.com/latotty) for this and many other improvements in this release!
=> Feat: Project Utils: source path options for buildAppSSR

packages/api-headless-cms/__tests__/mocks/parallelQueries.js, packages/api-headless-cms/__tests__/parallelQueries.test.js, packages/api-headless-cms/src/content/plugins/models.ts
One of our users noticed the following error happening while doing parallel querying via GraphQL:
The thing is, it's only happening when doing parallel queries, and also very randomly, which made it a bit harder to debug.
I did some research on how the `context` object is behaving when parallel queries are executed. It behaves like the following.
Let's say we have three queries. So, at the beginning of this whole operation, a new `context` object is created and is passed to all context plugins we have registered, **for every query**. This means that, if we are talking about the `context` plugin that is setting the models into the context object, we are setting models into the context **three times**, but everytime on the *same* `context` object!
And what's problematic here, since it's all …
=> Headless CMS - parallel GraphQL querying works correctly

packages/app-file-manager/src/admin/plugins/index.ts, packages/app-file-manager/src/admin/plugins/scopesList.ts
Closes #1255 
add missing `security-scopes-list` plugin in `app-file-manager`
Manually, using the Admin app UI and the GQL playground.
Played with resolvers that needed `files:file:crud` scope for example `getFile`
=> fix: add missing `security-scopes-list` plugin

package.json, packages/app-page-builder/src/render/plugins/elements/imagesList/ImagesList.tsx, packages/handler-apollo-gateway/package.json
Closes #1263 
Returned ListComponent and renamed the file to tsx
create new page -> add empty block -> add image list and select few images -> check both preview and edit mode that images are displayed
Had to lock apollo-server and apollo-server-core to 2.17.0 due to TS compiling error on 2.18.0-1
=> fix: display of image list in preview mode in PB

apps/admin/src/App.tsx, packages/app-plugin-security-cognito-theme/package.json, packages/app-plugin-security-cognito-theme/src/admin/types.ts, packages/app-plugin-security-cognito-theme/src/admin/views/StateContainer.tsx, packages/app-plugin-security-cognito-theme/tsconfig.build.json, packages/app-plugin-security-cognito-theme/tsconfig.json
Closes #1270 
Added plugin type that enables to change login logo in the administration
Registered plugin in apps/admin/src/App.tsx and checked in Webiny administration login page
Logo as a component example:
Logo as a src example:
Sample code (note that component is taken first and then src if there is no component):
```
plugins: [
{
type: "cognito-view",
name: "cognito-view-logo",
component() {
return (
<div style={{
background: 'grey',
textAlign: 'center',
padding: '5px',
color: 'white',
maxWidth: '500px',
margin: '0 auto',
}}>INSERTED LOGO COMPONENT</div>
);
},
src: 'https://picsum.photos/seed/picsum/100/100',
} as CognitoViewLogoPlugin,
],
```
=> feat(app-plugin-security-cognito-theme): plugin for to modify login logo

packages/app-page-builder/src/editor/components/IconPicker.tsx, packages/app-page-builder/src/editor/plugins/elementSettings/components/IconPicker.tsx, packages/app-page-builder/src/editor/plugins/elements/button/ButtonContainer.tsx, packages/app-page-builder/src/editor/plugins/elements/button/ButtonSettings.tsx, packages/app-page-builder/src/editor/plugins/elements/icon/IconSettings.tsx
Closes #379
Selected icon is first in the icons display grid and is greyed a bit. You can now click it to remove the selected icon.
Button:
add button -> select any icon -> publish and refresh -> go to settings and click on selected icon
Icon:
add icon -> go to settings -> select any other icon (there should be no possibility to remove selected icon in the icon list)
Button
Icon
=> feat(app-page-builder): add ability to remove selected icon on button

packages/api-headless-cms/src/content/apolloHandler/createApolloHandler.ts, packages/handler-apollo-gateway/src/gatewayHandler.ts, packages/handler-apollo-server/src/plugins/apolloHandler.ts
Closes #1283 
Remove redundant "server" option in "ApolloServer" constructor from:
- `@webiny/handler-apollo-server`
- `@webiny/handler-apollo-gateway`
- `@webiny/api-headless-cms`
Manually, by changing Changing `GRAPHQL_PLAYGROUND: false` in the `api/.env.json` and redeploying the API stack.
=> fix: remove redundant "server" args

packages/app-page-builder/src/editor/plugins/elements/row/RowChild.tsx
Closes #1258 
In some weird case that I haven't been able to reproduce, the `element.data` property becomes undefined, and further accessing values on it, in the `RowChild` component, throws an error (check code changes).
But that's not the worst part. The worst part is that the whole editor crashes, preventing the user from editing the page completely.
After some testing, I figured it's just better to handle this specific case in the mentioned `RowChild` component, and create a [separate issue](https://github.com/webiny/webiny-js/issues/1288) (since we'll be rebuilding PB with Recoil). Check the issue for more details.
N/A
=> Page Builder - handle missing object properties and prevent editor from crashing

packages/app-page-builder/src/admin/plugins/menuItems/link/LinkForm.tsx, packages/app-page-builder/src/editor/plugins/elementSettings/link/LinkSettings.tsx, packages/validation/__tests__/url.test.js, packages/validation/src/validators/url.ts
Closes #1260
The solution is to pass in allowRelative flag in the validator.
Existing tests in the url.test.js test the allowRelative flag.
=> fix: Allow Relative Paths in Page Builder Links.

packages/serverless-aws-s3/utils.js
fix(serverless-aws-s3): additional check for S3 Bucket name.
Closes #1294 
Checking the beginning of the bucket name is uppercase or not, if yes then should throw error.
NA
=> fix(serverless-aws-s3): additional check for S3 Bucket name.

.eslintignore, package.json
Closes #1251 
- changes made in `.eslintignore` file paths
- Have updated the `lint-staged` rules to check the `ts & tsx` file paths too
N/A
=> fix: configurations for development tools

packages/plugins/src/PluginsContainer.ts, packages/plugins/src/index.ts
Closes #1308 
Changed the `byType` method to no longer accept `undefined` as a valid type. Added the `all` method to `PluginsContainer` as the correct way to retrieve all plugins. 
I ran my changes against the existing tests, making sure that `plugins.test.js`, `modelFields.test.js`, `validators.test.js`, and `contentModelToSDL.test.js` passed in particular.
I also checked all uses of the `byType` method within the codebase to ensure that it was never being passed a value of `undefined` as a means for retrieving all plugins. As a result of this check, I updated the `getPlugins` function in `index.ts` to return all plugins when passed a value of `undefined`. This is expected behavior based on the tests found in `plugins.test.js`.
N/A
=> fix: correct behavior of plugins retrieval functions

packages/app-headless-cms/src/admin/views/ContentModels/NewContentModelDialog.tsx
Closes #1124 
Added a new custom validator to check the name pattern in `NewContentModelDialog` component. It will show messages inside the dialog if the name starts with a number or it equals `"id"`.  
For the name which starts with a number character: 
1. Open New Model dialog
2. Enter "3D Asset" or any other name which starts with a number for the model name.
3. Click Create button
For the name equals to `"id"`: 
1. Open New Model dialog
2. Enter "id" for the model name.
3. Click Create button
> 
Name starts with a number message:
Name equals to `"id"`:
=> fix: Content Model validation message for name field

packages/app-admin/src/plugins/Menu/Navigation/index.tsx, packages/project-utils/bundling/app/index.js
show published version of webiny in navigation sidebar footer in admin app
Closes #1195
Pulling version of webiny from `@webiny/project-utils/package.json` and setting it into an environment variable `REACT_APP_WEBINY_VERSION`. Using it in navigation sidebar
=> feat: show published version of webiny in admin app

packages/app-headless-cms/src/admin/plugins/fieldRenderers/DynamicSection.tsx
When added a multiple field to the model that already has some entries and then trying to edit some existing entry it would break because of the `bindField.value` being null.
=> fix(app-headless-cms): dynamic section breaks on bindField null value

packages/plugins/__tests__/plugins.test.js, packages/plugins/src/PluginsContainer.ts
Added internal cache when searching for plugins byType.
Cache is cleared when registering new plugin and when unregistering a plugin.
=> feat(plugins): add cache to search byType
