packages-api/webiny-entity-mysql/src/mysqlDriver.js, packages-api/webiny-entity-mysql/tests/findById.test.js, packages-api/webiny-entity-mysql/tests/findByIdError.test.js, packages-api/webiny-entity-mysql/tests/findByIds.test.js, packages-api/webiny-entity-mysql/tests/findByIdsError.test.js, packages-api/webiny-entity-mysql/tests/findError.test.js, packages-api/webiny-entity-mysql/tests/findOne.test.js, packages-api/webiny-entity/src/driverInterface.js, packages-api/webiny-entity/tests/customDriver.test.js
=> feat(webiny-entity-mysql): Enable finding entities not only by a single ID, but with an array of IDs

packages-api/webiny-api/package.json, packages-api/webiny-data-extractor/package.json, packages-api/webiny-entity-memory/package.json, packages-api/webiny-entity-mysql/package.json, packages-api/webiny-entity/package.json, packages-api/webiny-entity/src/entity.js, packages-api/webiny-entity/src/entityAttributes/entityAttribute.js, packages-api/webiny-entity/tests/attributes/entityAttribute.test.js, packages-api/webiny-entity/tests/driver.test.js, packages-api/webiny-entity/tests/entities/numbers.js, packages-api/webiny-model/package.json, packages-api/webiny-sql-query-builder/package.json
=> test(webiny-entity): Test entity attribute

packages/webiny-app-cms/src/plugins/editor/elementSettings/border/Settings.js
=> fix: 🐛  Update border settings to use the new color picker.

packages/webiny-ui/src/Avatar/Avatar.js, packages/webiny-ui/src/Avatar/Avatar.stories.js, packages/webiny-ui/src/Avatar/README.md, packages/webiny-ui/src/Avatar/index.js
Create Avatar component. 
affects: webiny-ui
=> feat: ✨  Implement Avatar component.

packages/webiny-app-admin/src/plugins/UserMenu/plugins/UserInfo/UserInfo.js
affects: webiny-app-admin
ISSUES CLOSED: fixes #149
=> fix: 🐛  Fixes empty avatar in UserMenu.

packages/webiny-app-admin/src/plugins/UserMenu/plugins/UserInfo/UserInfo.js
affects: webiny-app-admin
ISSUES CLOSED: #150
=> fix: 🐛  Fixes user name overflow for long names.

packages/demo-admin/src/userIdentity.js, packages/demo-api/src/configs/development.js, packages/webiny-api/src/entities/Entity/Entity.graphql.js, packages/webiny-api/src/entities/Entity/Entity.js, packages/webiny-api/src/entities/Entity/Group.mysql.js, packages/webiny-api/src/entities/Entity/Policy.mysql.js, packages/webiny-api/src/entities/User/User.entity.js, packages/webiny-api/src/install/entities/groupDefault.js, packages/webiny-api/src/install/entities/index.js, packages/webiny-api/src/install/entities/policyFilesOwnersAccess.js, packages/webiny-api/src/install/entities/policySecurityFullAccess.js, packages/webiny-api/src/install/entities/policySecurityUserAuthentication.js, packages/webiny-api/src/install/entities/policySuperAdmin.js, packages/webiny-api/src/install/importData.js, packages/webiny-app-admin/src/plugins/UserMenu/plugins/UserImage/UserImage.js, packages/webiny-app-admin/src/plugins/UserMenu/plugins/UserInfo/UserInfo.js, packages/webiny-app-admin/src/views/ApiTokens/ApiTokensDataList.js, packages/webiny-app-admin/src/views/Groups/GroupsDataList.js, packages/webiny-app-admin/src/views/Groups/GroupsForm.js, packages/webiny-app-admin/src/views/Groups/PoliciesAutoComplete.js, packages/webiny-app-admin/src/views/Policies/PoliciesDataList.js, packages/webiny-app-admin/src/views/Policies/PoliciesForm.js, packages/webiny-app-admin/src/views/Policies/PoliciesForm/PolicyEditorDialog.js, packages/webiny-app-admin/src/views/Users/UsersDataList.js, packages/webiny-app-admin/src/views/Users/UsersForm.js, packages/webiny-ui/src/Button/IconButton/IconButton.js
This pull request will resolve following issues:
=> Security Issues

packages/webiny-app-cms/src/editor/presets/default.js
=> Disable desktop/mobile preview plugins

packages/webiny-app-cms/src/admin/views/Categories/Categories.js, packages/webiny-app-cms/src/admin/views/Categories/CategoriesDataList.js, packages/webiny-app-cms/src/admin/views/Categories/CategoriesForm.js, packages/webiny-app-cms/src/admin/views/Categories/validators.js
=> Link theme layouts with Categories form.

packages/webiny-app-admin/src/plugins/SearchBar/SearchBar.js, packages/webiny-app-admin/src/plugins/SearchBar/styled.js
=> feat: ✨  New search box design.

packages/webiny-app-cms/src/editor/plugins/blockEditing/AutoScale.js, packages/webiny-app-cms/src/editor/plugins/blockEditing/SearchBlocks.js, packages/webiny-app-cms/src/editor/plugins/blockEditing/StyledComponents.js, packages/webiny-app-cms/src/editor/plugins/elements/image/Image.js
=> Fix scaling of block preview.

packages/webiny-app-cms/src/editor/plugins/elementSettings/Action.js, packages/webiny-app-cms/src/editor/plugins/toolbar/Action.js
=> fix: 🐛  Fixed icon active status on toolbar and element settings.

packages/demo-theme/src/style/elements/typography.scss, packages/demo-theme/src/style/variables.scss, packages/webiny-app-admin/src/views/Login.js
=> Login error message and theme font color.

packages/webiny-app-admin/src/plugins/UserMenu/plugins/UserInfo/UserInfo.js, packages/webiny-app-admin/src/views/Users/UsersDataList.js, packages/webiny-ui/src/Avatar/Avatar.js, packages/webiny-ui/src/List/DataList/DataList.js
=> Fix font color and width on Avatar component

packages/webiny-app-cms/src/editor/components/DropZone/Horizontal.js, packages/webiny-app-cms/src/editor/components/DropZone/Vertical.js
=> feat: ✨  Dropzones are only visible on hover.

packages/webiny-api-cms/src/dataSource/schemas/Page.schema.js, packages/webiny-api-cms/src/dataSource/schemas/Revision.schema.js, packages/webiny-api-cms/src/entities/Page.entity.js, packages/webiny-api-cms/src/entities/Page.mysql.js, packages/webiny-api-cms/src/entities/Revision.entity.js, packages/webiny-api-cms/src/entities/Revision.mysql.js, packages/webiny-app-cms/src/admin/graphql/pages.js, packages/webiny-app-cms/src/admin/plugins/pageDetails/pageRevisions/CreateRevisionDialog.js, packages/webiny-app-cms/src/admin/plugins/pageDetails/pageRevisions/Revision.js, packages/webiny-app-cms/src/admin/views/Pages/Pages.js, packages/webiny-app-cms/src/admin/views/Pages/PagesDataList.js, packages/webiny-app-cms/src/editor/plugins/defaultBar/Title.js, packages/webiny-app-cms/src/editor/redux/index.js
This PR adds revision version number to API and UI.
It also fixes #241.
=> Add revision version number

packages/webiny-app-cms/src/editor/plugins/defaultBar/Styled.js, packages/webiny-app-cms/src/editor/plugins/defaultBar/Title.js
=> Handle page title using Esc, Enter and blur events.

packages/webiny-app-cms/src/editor/plugins/blockEditing/StyledComponents.js
=> Limit block list max width.

packages/webiny-app-cms/src/editor/components/Element/ElementStyled.js, packages/webiny-app-cms/src/editor/plugins/elements/media/youtube/YoutubeEmbed.js
=> Fixes element select state overlay border

packages/webiny-app-cms/src/admin/plugins/menuItems/folder/FolderForm.js, packages/webiny-app-cms/src/admin/plugins/menuItems/link/LinkForm.js, packages/webiny-app-cms/src/admin/plugins/menuItems/page/PageForm.js, packages/webiny-app-cms/src/admin/plugins/menuItems/pageList/PageListForm.js, packages/webiny-app-cms/src/admin/views/Menus/MenusForm/MenuItems.js, packages/webiny-app-cms/src/admin/views/Menus/MenusForm/MenuItems/MenuItemRenderer.css, packages/webiny-app-cms/src/admin/views/Menus/MenusForm/MenuItems/MenuItemRenderer.js, packages/webiny-app-cms/src/admin/views/Menus/MenusForm/MenuItems/MenuItemsList.js
=> Menu visual styling

packages/webiny-app-cms/src/editor/plugins/elementSettings/background/Settings.js, packages/webiny-app-cms/src/editor/plugins/elementSettings/components/Select.js
=> Fixed "scaling" select in background image settings

packages/webiny-app-admin/src/styles/material-theme-assignments.scss, packages/webiny-app-cms/src/editor/plugins/elementSettings/save/SaveDialog.js
=> Fixes dialog overflow and save block image preview.

packages/webiny-app-cms/src/editor/plugins/toolbar/addElement/StyledComponents.js
=> Fix scrolling of elements in the toolbar.

packages/webiny-api-cms/src/install/importData/staticPages/error.js, packages/webiny-api-cms/src/install/importData/staticPages/homepage.js, packages/webiny-api-cms/src/install/importData/staticPages/notFound.js, packages/webiny-app-cms/src/editor/plugins/elementSettings/align/HorizontalAlignAction.js, packages/webiny-app-cms/src/editor/plugins/elementSettings/align/VerticalAlignAction.js, packages/webiny-app-cms/src/editor/plugins/elementSettings/background/Settings.js, packages/webiny-app-cms/src/editor/plugins/elementSettings/border/Settings.js, packages/webiny-app-cms/src/editor/plugins/elementSettings/components/PMSettings.js, packages/webiny-app-cms/src/editor/plugins/elementSettings/height/Settings.js, packages/webiny-app-cms/src/editor/plugins/elementSettings/shadow/Settings.js, packages/webiny-app-cms/src/editor/plugins/elementSettings/width/Settings.js, packages/webiny-app-cms/src/editor/plugins/elements/row/index.js, packages/webiny-app-cms/src/editor/plugins/elements/text/Text.js, packages/webiny-app-cms/src/editor/plugins/elements/text/index.js, packages/webiny-app-cms/src/render/components/ElementStyle.js, packages/webiny-app-cms/src/render/plugins/elementSettings/align/index.js, packages/webiny-app-cms/src/render/plugins/elementSettings/background/index.js, packages/webiny-app-cms/src/render/plugins/elementSettings/border/index.js, packages/webiny-app-cms/src/render/plugins/elementSettings/height/index.js, packages/webiny-app-cms/src/render/plugins/elementSettings/index.js, packages/webiny-app-cms/src/render/plugins/elementSettings/margin/index.js, packages/webiny-app-cms/src/render/plugins/elementSettings/padding/index.js, packages/webiny-app-cms/src/render/plugins/elementSettings/shadow/index.js, packages/webiny-app-cms/src/render/plugins/elementSettings/width/index.js, packages/webiny-app-cms/src/render/presets/default.js, packages/webiny-app-cms/src/types.js
This PR introduces new render plugins for element styles.
This way we can control what CSS styles are applied to an element based on `element-settings` plugins. It also allows further render optimizations that will be handled in a separate PR.
=> Introduce element style render plugins.

packages/demo-api/src/install/install.js, packages/demo-api/src/plugins.js, packages/demo-site/src/plugins/index.js, packages/webiny-api-cms/src/plugins/index.js, packages/webiny-api/src/plugins/index.js, packages/webiny-app-cms/src/editor/plugins/defaultBar/components/PageOptionsMenu.js, packages/webiny-app-cms/src/editor/plugins/defaultBar/components/PreviewPageButton.js, packages/webiny-app-cms/src/editor/plugins/defaultBar/index.js, packages/webiny-app-cms/src/editor/plugins/elements/code/index.js, packages/webiny-app-cms/src/editor/plugins/elements/social/index.js, packages/webiny-app-cms/src/render/plugins/elementSettings/index.js, packages/webiny-plugins/src/__tests__/plugins.test.js, packages/webiny-plugins/src/index.js
=> Moved "Preview" button into page options dropdown

packages/demo-api/src/files/create.js
=> Images uploaded locally will be optimized

packages/demo-admin/src/config/index.js, packages/demo-api/package.json, packages/webiny-app-cms/src/editor/plugins/elementSettings/advanced/AdvancedAction.js, packages/webiny-app-cms/src/editor/plugins/elementSettings/advanced/AdvancedSettings.js, packages/webiny-app-cms/src/editor/plugins/elementSettings/advanced/index.js, yarn.lock
Advanced settings  action will check if it needs to be rendered by checking plugins registered for the active element.
=> Check whether advanced plugins are registered for active element. 

packages/webiny-app-cms/src/render/plugins/slate/italic/index.js, packages/webiny-app/package.json, packages/webiny-entity-mongodb/package.json, yarn.lock
=> Update italic plugin type.

packages/webiny-ui/src/Menu/Menu.js
=> Fix menu container positioning.

packages/webiny-app-cms/src/editor/plugins/blockEditing/BlockPreview.js, packages/webiny-app-cms/src/editor/plugins/blockEditing/BlocksList.js
=> Fix blocks list  item height recalculation.

packages/webiny-ui/src/ImageEditor/ImageEditor.js, packages/webiny-ui/src/ImageUpload/ImageEditorDialog.js
=> When closing the image editor and then opening the same image again, a new editing session will be started

packages/demo-api/package.json, packages/webiny-app-cms/src/editor/plugins/elementSettings/link/LinkSettings.js, packages/webiny-app-cms/src/editor/plugins/elements/image/ImageContainer.js, packages/webiny-app-cms/src/render/plugins/elements/image/Image.js, packages/webiny-app/src/components/SingleImageUpload.js, packages/webiny-plugins/package.json, packages/webiny-plugins/src/index.js, yarn.lock
This PR fixes minor bugs with button and image `link` rendering as well as Image component `width` rendering in the editor.
=> CMS Editor fixes

packages/webiny-form/src/Form.js, packages/webiny-validation/__tests__/password.test.js, packages/webiny-validation/src/validators/password.js
This PR fixes form validation on dotted input names and adds password validator parameter to control password length.
=> Validation improvement.

packages/webiny-app-cms/src/editor/plugins/elements/pagesList/PagesList.js, packages/webiny-app-cms/src/editor/plugins/elements/pagesList/graphql.js
=> "List of pages" element - fixed pages settings

packages/demo-theme/src/components/DefaultMenu.js, packages/webiny-api-cms/src/plugins/graphql/menuResolvers/prepareMenuItems.js, packages/webiny-app-cms/src/admin/plugins/menuItems/page/PageForm.js, packages/webiny-ui/src/AutoComplete/AutoComplete.js, packages/webiny-ui/src/Input/Input.js
=> By default, page menu item for its title uses selected page's title

independent/webiny-cli/src/init/template/packages/site/src/plugins/index.js, packages/demo-site/src/plugins/index.js
=> Fix cookie policy plugins import in site app.

packages/webiny-app-cms/src/editor/plugins/defaultBar/components/PublishPageButton.js
=> When editing a new revision in editor, top right "Publish" button would now have "Publish changes" label (better UX)

packages/webiny-app-cms/src/editor/plugins/elementSettings/components/Action.js, packages/webiny-app-cms/src/editor/plugins/elementSettings/delete/index.js
This PR adds handling of `delete` key in addition to the existing `backspace` key, to delete editor elements. `Action` component is also upgraded to support handling of multiple shortcuts.
=> Delete element using "delete" key.

packages/webiny-app-mailchimp/README.md, packages/webiny-app-mailchimp/src/admin/components/MailchimpElementAdvancedSettings.js
During the migration of Webiny to `react-router`, this package remained unpublished.
Using this opportunity to both trigger publishing of the package and update the README which was entirely outdated.
=> Migrate webiny-app-mailchimp to react-router.

packages/webiny-api-cms/src/entities/CmsSettings.entity.js, packages/webiny-api-cms/src/entities/Page.entity.js, packages/webiny-api-cookie-policy/src/index.js, packages/webiny-api-files/src/entities/File.entity.js, packages/webiny-api-google-tag-manager/src/index.js, packages/webiny-api-mailchimp/src/index.js, packages/webiny-api-security/src/plugins/security.js, packages/webiny-api/src/entities/Settings.entity.js, packages/webiny-api/src/graphql/crudResolvers.js, packages/webiny-api/src/lambda/lambda.js, packages/webiny-api/src/plugins/graphqlContextEntities.js
Simplified the registration and usage of entities, more specifically, getting entity classes.
Old classes were not refactored to the new mechanism, it is backward compatible (although in the near future we should refactor existing).
=> Simplified entities registration and usage (API)

packages/app-forms/src/admin/plugins/menus.js, packages/app-forms/src/admin/plugins/routes.js, packages/app-forms/src/admin/plugins/settings/index.js
Changed Forms label to Form Builder and changed page title, too.
=> changed form label and title

packages/cli/create/template/apps/site/handler/handler.js, packages/cli/create/template/apps/site/package.json, yarn.lock
https://github.com/webiny/webiny-js/issues/626
=> enabled gzip compression

examples/packages/project-utils/cra/sass.js
Fixed SASS config according to the changelog
https://webpack.js.org/loaders/sass-loader/#sassoptions
=> fix sass options

components/serverless-files/serverless.js
Fixes #647.
Removed the bucket deletion step.
=> Do not delete the S3 bucket, users must delete it manually

README.md
Remove trailing whitespace.  Use HTML5 style `br` and `img` tags.
Minor fixes and I can open an issue if needed.
=> fix: broken link in README.

packages/cli/cli.js
=> fix(cli): Handle unknown commands

packages/cli/cli.js
Follow up of #660 
Recommends matching commands if the user mistypes.
=> feat(cli): recommend matching commands

packages/api-form-builder/src/plugins/graphql/formResolvers/listPublishedForms.ts
#687
Added `await` where missing. 
N/A
=> Add missing `await` in `listPublishedForms` resolver

components/serverless-db-proxy/serverless.js, examples/api/serverless.yml, examples/apps/serverless.yml, packages/cli/create/template/api/serverless.yml, packages/cli/create/template/apps/serverless.yml
#706 
Added connection establishment in the `serverless-db-proxy` component.
=> feat(db-proxy): test connection before deploying

packages/http-handler-ssr/src/ssrServe.ts
=> fix: send "refresh" flag to actually trigger the refresh

packages/http-handler-ssr/src/functions/parseBody.ts, packages/http-handler-ssr/src/ssrCacheApi.ts
=> fix: parse JSON only if string

packages/app-page-builder/src/render/plugins/elements/button/Button.tsx, packages/app-page-builder/src/render/plugins/elements/image/Image.tsx, packages/react-router/src/Link.tsx, yarn.lock
#719 
Replaced the Link components with a.
Manually tested in local environment.
=> Updated link for button and image

package.json, packages/app-page-builder-theme/package.json, packages/app-page-builder/package.json, packages/cli/sls/deploy.js, yarn.lock
close #685 
I have changed the error message of `webiny deploy-apps` to be more descriptive so that it's a little bit more descriptive
1. run `webiny deploy-apps --env=dev` with prerequisites of not having  dev environment .env.json files in apps
2. there will be an error saying
```
Environment {name of environment} is missing {app path}/.env.json file.
Have you deployed the corresponding API environment?
To deploy the API, run "webiny deploy-api --env=dev."
```
=> Changed error message of deploy apps to be more descriptive

examples/apps/admin/README.md, examples/apps/site/README.md, packages/cli/create/template/apps/admin/README.md, packages/cli/create/template/apps/site/README.md
=> Updated React URL links

packages/app-page-builder-theme/src/components/Navigation.tsx, packages/app-page-builder-theme/src/styles/elements/header-nav.scss
https://github.com/webiny/webiny-js/issues/737
I wrapped `<li>` item in `<Link>` component. Also refactor `getLink` method
This was tested by clicking outside  of text on navigation item
=> fix: Navigation link padding

packages/api-i18n/src/plugins/service.ts
https://github.com/webiny/webiny-js/issues/748
I added validation for valid url inside `packages/api-i18n/src/plugins/service.ts`
I don't know how this could be tested
=> I18N Service Plugins - Improved error messaging 

packages/app-admin/src/types.ts, packages/app/src/types.ts
closes #770
Added `type`, `description` and `links` to plugin documentation to improve the developer experience when using IDEs.
Manual testing
=> Improved descriptions for "route", "menu", and "header-*" plugins

packages/form/src/Bind.ts
close #759 
Disabled props was hard coded as mentioned in #759 and so i followed the directions by @doitadrian 
not tested yet actually
=> fix: 🐛  fixed storybook disabled input and select was hard coded

packages/app-page-builder/src/editor/components/IconPicker.tsx
- add icons as a dependency on `renderGrid` useCallback
- fix missing search input placeholder in Icon picker when using Dark mode
- improve search by trimming whitespaces from the filter
Page builder: Search is not working in Icon picker component
Issue https://github.com/webiny/webiny-js/issues/793
1. Add `icons` as a dependency to `renderGrid` useCallback
2. Add opacity property to search input placeholder to fix missing search input placeholder in Icon picker when using Dark mode
3. Improve search by trimming whitespaces from the filter
1. Run admin app and visit http://localhost:3001/admin/page-builder/pages
2. Select a page to edit and add a button block to the page
3. Click the button to change its settings and then click on the Icon tab
4. Click the Icon to open up IconPicker
5. …
=> Added icons as a dependency to "renderGrid" and "useCallback".

packages/api-headless-cms/package.json, packages/api-security/package.json, packages/project-utils/package.json
fix the wrong packages version for headless-latest branch
BREAKING CHANGE:
none
=> fix: 🐛  fix the wrong packages version

package.json, scripts/webinyVersions.js
Added a simple `webiny-versions` script that will update package versions inside of the `sample-project` folder.
By @Ashu96.
=> Added webiny-versions script

packages/app-form-builder/src/admin/plugins/fields/components/OptionsList.tsx
allow user to select single checkbox
BREAKING CHANGE:
none
=> feat: ✨  Single checkbox form field

packages/app-admin/src/types.ts
A related issue is in the docs repo [here](https://github.com/webiny/docs.webiny.com/issues/69)
As we are in the process of updating the admin plugin reference in docs, we should also update them in source code
Please feel free to decline if not relevant
=> docs: 📚  Update admin plugin reference in source code

CHANGELOG.md, lerna.json, packages/app-form-builder-theme/CHANGELOG.md, packages/app-form-builder-theme/package.json, packages/app-form-builder/CHANGELOG.md, packages/app-form-builder/package.json, packages/app-headless-cms/CHANGELOG.md, packages/app-headless-cms/package.json, packages/app-i18n/CHANGELOG.md, packages/app-i18n/package.json, packages/app-i18n/src/admin/plugins/install.tsx, packages/app-plugin-security-cognito-theme/CHANGELOG.md, packages/app-plugin-security-cognito-theme/package.json, packages/app-template-admin-full/CHANGELOG.md, packages/app-template-admin-full/package.json, packages/app-template-admin/CHANGELOG.md, packages/app-template-admin/package.json, packages/app-template-site/CHANGELOG.md, packages/app-template-site/package.json, packages/create-webiny-project/init.js, packages/cwp-template-cms/index.js, packages/cwp-template-full/index.js
=> chore: ⚡️  Add yarn to webiny function call

docs/CONTRIBUTING.md
N.A
Small change to CONTRIBUTING.md to fix a broken link
Manually
N.A
=> docs: update broken link in CONTRIBUTING.md

packages/app-form-builder/src/admin/plugins/formDetails/formSubmissions/FormSubmissionsList/FormSubmissionsList.tsx, packages/app-form-builder/src/types.ts, packages/app/src/hooks/useDataList/useDataList.ts
Added a new plugin - more details can be found on the following link:
https://docs.webiny.com/docs/webiny-apps/form-builder/development/plugins-reference/app#fb-form-details-submissions-list-multi-select-action
=> Form Builder - added "fb-form-details-submissions-list-multi-select-action" plugin

packages/app-form-builder/src/admin/components/FormEditor/Fields.tsx
Closes #1032 
Fix contact information group not working. Update accordion-item styles
https://www.loom.com/share/4bae9147561f481a8a575ef4c04fe2a6
=> Fix: Form Builder - Contact Information group not working

packages/app-template-admin-full/README.md, packages/app-template-admin/README.md, packages/app-template-site/README.md, packages/app-template/README.md, packages/app/README.md
None
Update the official docs link in readme
Manually
=> Fix: update official docs link

packages/app-template-admin/src/index.tsx
Closes #768 
Redirect unknown routes to the default route.
Manually
[![Gif](https://cdn.loom.com/sessions/thumbnails/6b7bbcd382d9479c8b2a78dca3613259-with-play.gif)](https://www.loom.com/share/6b7bbcd382d9479c8b2a78dca3613259)
=> Admin - when trying to visit an unexisting route, users will be redirected to the default route

packages/app-mailchimp/src/admin/components/MailchimpElement.tsx, packages/app-mailchimp/src/admin/components/MailchimpElementAdvancedSettings.tsx, packages/app-mailchimp/src/admin/components/MailchimpSettings.tsx, packages/app-mailchimp/src/render/components/MailchimpDefaultForm.tsx
Closes #618 
```tsx
import { i18n } from "@webiny/app/i18n";
const t = i18n.ns("app-mailchimp/admin");
```
Now wrap strings into `t` template literal
Manually
=> feat: i18n for the mailchimp app

packages/app-form-builder/src/components/Form/FormRender.tsx
Closes #1069 
Replace `I18NValue` with `useI18N` getValue
https://www.loom.com/share/bd552494786d496f80198cda4e357862
=> Fix: Form Builder- field validation message

packages/api-headless-cms/__tests__/environments.test.js, packages/api-headless-cms/src/plugins/graphql/environment.ts, packages/api-headless-cms/src/plugins/models/environment.model.ts, packages/api-headless-cms/src/testing/createEnvironmentAlias.ts, packages/api-headless-cms/src/testing/index.ts, packages/app-headless-cms/src/admin/components/EnvironmentSelectorDialog.tsx, packages/app-headless-cms/src/admin/contexts/Cms/graphql.ts, packages/app-headless-cms/src/admin/views/Environments/EnvironmentsDataList.tsx, packages/app-headless-cms/src/admin/views/Environments/graphql.ts
Closes #1071 
Upgrade `CmsEnvironment` to have an array of aliases rather than a single alias
- API: Using `jest` test
- UI: Manually using the Admin app
https://www.loom.com/share/5d67c34cf2ed489f97db8031c8b06fd9
=> Feat: Upgrade `CmsEnvironment` type

docs/DEVELOPMENT_OVERVIEW.md
Add Development Overview article in docs
=> docs(contributions doc): add development overview doc

packages/app-form-builder/src/admin/plugins/welcomeScreenWidget.tsx, packages/app-headless-cms/src/admin/plugins/welcomeScreenWidget.tsx, packages/app-page-builder/src/admin/plugins/welcomeScreenWidget.tsx, packages/app-plugin-admin-welcome-screen/src/components/Welcome.tsx
Closes #1074
Attempting to hide ```welcomeScreenWidget```s from unauthorised users, as they should not have access to if they're not authorised to use them.\
Using ```app-form-builder``` as a first attempt.
My initial attempt was to do it from each welcomeScreenWidget but I only could manage to hide the link button. Here is what it looked like:
So I then applied SecureView to each mapped out Widget plugin from ```app-plugin-admin-welcome-screen/src/components/Welcome.tsx``` file, while passing in a scopes key from the app-form-builder welcomeScreenWidget plugin.
From both unauthorized and authorized accounts, here are the results as it appears to work:
@EmilK15 what do you think? Should I keep the Secure View from the Welcome.tsx file instead and just pass in Secure View scopes from …
=> fix: Hiding widgets / links from unauthorized users on welcome screen.

packages/app-plugin-admin-welcome-screen/src/components/Welcome.tsx
Closes #1115 
- fix styles for mobile view
- add missing `alt` text for images.
Manually using the Admin app UI
https://pasteboard.co/JgZO3Ie.png
=> Update styles for mobile view

docs/CONTRIBUTING.md
remove reference of sample-project
=> Fix: contributing doc

packages/cli-plugin-scaffold-admin-app-module/index.js, packages/cli-plugin-scaffold-graphql-service/index.js, packages/cli-plugin-scaffold-graphql-service/package.json, packages/cli-plugin-scaffold-lambda/index.js, packages/cli-plugin-scaffold-lambda/package.json, packages/cli-plugin-scaffold-node-package/index.js, packages/cli-plugin-scaffold-node-package/package.json, packages/cli-plugin-scaffold-react-app/index.js, packages/cli-plugin-scaffold-react-app/package.json, packages/cli-plugin-scaffold-react-package/index.js, packages/cli-plugin-scaffold-react-package/package.json, packages/cli-plugin-scaffold/index.js
N/A
I improved the UX on existing scaffolds by adding additional messaging. 
=> Improving UX on existing scaffolds

packages/project-utils/bundling/app/createDevConfig.js
Closes #1214
Checking for undefined instead of falsy.
Tested locally against my project. (Mirrored the changes [1 line] into my node_modules, because I didn't set up proper webiny dev env atm.)
=> fix: Project Utils: fix default openBrowser value

packages/cli-plugin-scaffold-lambda/index.js, packages/cli-plugin-scaffold-lambda/template/src/index.ts, packages/cli-plugin-scaffold-node-package/index.js, packages/cli-plugin-scaffold-node-package/template/package.json, packages/cli-plugin-scaffold-react-app/index.js, packages/cli-plugin-scaffold-react-package/index.js, packages/cli-plugin-scaffold-react-package/template/package.json
We fixed a couple of hiccups in our existing scaffolding tools, and while we were at it, added some minor polishes, to make the whole experience more pleasant. 
N/A
**Title**: Polished existing scaffolding tools
**Body**: We fixed a couple of hiccups in our existing scaffolding tools, and while we were at it, added some minor polishes, to make the whole experience more pleasant.
=> Scaffolding - minor bug fixes and polishes

api/apolloGateway/package.json, api/cms/content/package.json, api/cms/dataManager/package.json, api/cms/graphql/package.json, api/databaseProxy/package.json, api/files/download/package.json, api/files/graphql/package.json, api/files/manage/package.json, api/files/transform/package.json, api/formBuilder/package.json, api/i18n/graphql/package.json, api/i18n/locales/package.json, api/pageBuilder/package.json, api/security/graphql/package.json, api/security/permissionsManager/package.json, api/security/validateAccessToken/package.json, api/settingsManager/package.json, apps/admin/package.json, apps/adminSlate/package.json, apps/cmsOnly/package.json, apps/databaseProxy/package.json, apps/site/package.json
Update Webiny packages version in `api/*` and `apps/*` using `yarn run webiny-versions` command.
=> Fix: Webiny packages version

packages/ui/src/Button/Button.tsx, packages/ui/src/Button/index.ts
No issue
Exported types from the UI Buttons.
`yarn build`
=> Feat: UI: export Button types

packages/app-security/README.md
=> docs: Remove duplicate word

.github/stale.yml, .github/workflows/greetings.yml, .github/workflows/stale.yml
Closes #1289 
For the Action to work successfully run it needs GITHUB_TOKEN which I don't have permission for this Repository so reviewers kindly please feel free to try .github/workflow/greetings.yml before merging it :)
I have added 2 Github Actions which does 2 task
Greeting Bot
* Gives a warm welcome personalized message to Contributors <br>
Stale Bot
* Marks Issues which have seen no activity for 120 days as stale and it is closed within the next 30 days with a message.
* Maintainers can change this duration at the .github/stale.yml file. I have added comments to make it easier to understand and work with.
I have used this bot on a lot of my Open Source Projects and on projects that I am a maintainer of. Made me live so much easy as the Project picked up.
=> feat: Greetings and Stale Bot

apps/admin/code/src/plugins/pageBuilder/editorPlugins.ts, packages/app-page-builder/src/editor/hooks/useKeyHandler.ts, packages/app-page-builder/src/editor/plugins/elements/grid/index.tsx, packages/app-page-builder/src/editor/plugins/elements/index.ts
Fix for grid settings plugin loading.
Also fixed check if contentEditable is currently selected element
=> fix: grid settings plugin

packages/app-form-builder/src/components/Form/Form.tsx, packages/app-form-builder/src/components/Form/FormLoad.tsx, packages/app-form-builder/src/page-builder/admin/plugins/components/FormElementAdvancedSettings.tsx, packages/app-form-builder/src/page-builder/admin/plugins/components/graphql.js, packages/app-form-builder/src/page-builder/admin/plugins/index.tsx
Migrate `Form` component for `Page builder`.
=> Feat: migrate `FB` form component for `PB`

packages/api-headless-cms/src/content/plugins/crud/contentEntry/elasticSearchHelpers.ts
Simplify es helpers and use cloneDeep at some points
=> refactor: simplify elasticsearch helpers
